import {
  Lightbulb,
  Code,
  FileText,
  Search,
  Languages,
  BookOpen,
  Briefcase,
  Mail,
  PenTool,
  BarChart,
  MessageSquare,
  Sparkles,
  Brain,
  Database,
  GitBranch,
  Bug,
  Rocket,
  Target,
  TrendingUp,
  CheckCircle,
  DollarSign,
  Users,
  Headphones,
  Package,
  Calculator,
  UserCheck,
  Phone,
  Handshake,
  Award,
  Presentation,
} from "lucide-react";

export interface PromptTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  prompt: string;
  icon: any;
  variables?: string[];
  tags: string[];
  featured?: boolean;
}

export const promptCategories = [
  { id: "sales", name: "Sales", icon: DollarSign },
  { id: "business", name: "Business", icon: Briefcase },
  { id: "support", name: "Support", icon: Headphones },
  { id: "hr", name: "HR", icon: Users },
  { id: "creative", name: "Creative", icon: Lightbulb },
  { id: "code", name: "Code", icon: Code },
  { id: "writing", name: "Writing", icon: PenTool },
  { id: "analysis", name: "Analysis", icon: BarChart },
  { id: "research", name: "Research", icon: Search },
  { id: "learning", name: "Learning", icon: BookOpen },
  { id: "productivity", name: "Productivity", icon: Target },
];

export const promptTemplates: PromptTemplate[] = [
  // Sales Prompts
  {
    id: "cold-outreach",
    title: "Cold Outreach Email (SDR)",
    description: "Craft compelling cold outreach for prospects",
    category: "sales",
    prompt: "Create a cold outreach email for {prospect_title} at {company} in the {industry} industry. Our solution: {solution}. Include:\n- Attention-grabbing subject line\n- Personalized opening\n- Clear value proposition\n- Specific pain point we solve\n- Soft CTA for discovery call\n- Keep it under 100 words",
    icon: Mail,
    variables: ["prospect_title", "company", "industry", "solution"],
    tags: ["sales", "sdr", "outreach", "cold-email"],
    featured: true,
  },
  {
    id: "discovery-questions",
    title: "Discovery Call Questions",
    description: "Prepare effective discovery questions",
    category: "sales",
    prompt: "Create a comprehensive discovery question framework for selling {product/service} to {buyer_persona}. Include:\n- 10 open-ended questions using SPIN methodology\n- Questions about situation, problem, implication, and need-payoff\n- Follow-up probes for each\n- Red flags to watch for\n- Qualification criteria",
    icon: MessageSquare,
    variables: ["product/service", "buyer_persona"],
    tags: ["sales", "discovery", "questions", "spin"],
    featured: true,
  },
  {
    id: "objection-handling",
    title: "Objection Handling Scripts",
    description: "Handle common sales objections effectively",
    category: "sales",
    prompt: "Create objection handling scripts for: {objection}. Provide:\n- 3 different response frameworks\n- Empathy statement\n- Reframe technique\n- Proof points/case studies to reference\n- Follow-up questions\n- When to walk away",
    icon: CheckCircle,
    variables: ["objection"],
    tags: ["sales", "objections", "closing"],
  },
  {
    id: "sales-proposal",
    title: "Sales Proposal (AE)",
    description: "Create winning sales proposals",
    category: "sales",
    prompt: "Draft a sales proposal for {prospect_company} for {solution}. Deal size: {deal_size}. Include:\n- Executive summary\n- Current challenges identified\n- Proposed solution and ROI\n- Implementation timeline\n- Pricing and packages\n- Success metrics\n- Next steps",
    icon: FileText,
    variables: ["prospect_company", "solution", "deal_size"],
    tags: ["sales", "proposal", "closing"],
  },
  {
    id: "follow-up-sequence",
    title: "Follow-Up Sequence",
    description: "Multi-touch follow-up campaign",
    category: "sales",
    prompt: "Create a 5-touch follow-up sequence for {scenario}. Include:\n- Email 1 (Day 1): Thank you + recap\n- Email 2 (Day 3): Value-add content\n- Email 3 (Day 7): Case study/social proof\n- Email 4 (Day 14): Alternative approach\n- Email 5 (Day 21): Break-up email\nInclude subject lines and recommended send times.",
    icon: Target,
    variables: ["scenario"],
    tags: ["sales", "follow-up", "cadence"],
  },
  {
    id: "sales-battlecard",
    title: "Competitive Battlecard",
    description: "Win against competitors",
    category: "sales",
    prompt: "Create a competitive battlecard for selling against {competitor}. Include:\n- Their key strengths\n- Their weaknesses/gaps\n- Our differentiators\n- Win themes\n- Trap-setting questions\n- Landmines to avoid\n- Proof points and case studies",
    icon: Award,
    variables: ["competitor"],
    tags: ["sales", "competitive", "battlecard"],
  },
  {
    id: "csm-onboarding",
    title: "Customer Onboarding Plan (CSM)",
    description: "Successful customer onboarding",
    category: "sales",
    prompt: "Create a 90-day onboarding plan for {customer} (ARR: {arr}). Include:\n- Week 1-2: Setup and training\n- Week 3-4: First value milestone\n- Month 2: Adoption expansion\n- Month 3: Success review and upsell prep\n- Key stakeholders to engage\n- Success metrics to track\n- Risk mitigation strategies",
    icon: UserCheck,
    variables: ["customer", "arr"],
    tags: ["csm", "onboarding", "customer-success"],
  },
  {
    id: "renewal-strategy",
    title: "Renewal Strategy (CSM)",
    description: "Maximize renewals and expansion",
    category: "sales",
    prompt: "Develop a renewal strategy for {customer} (renewal date: {date}, ARR: {arr}). Current health score: {health}. Include:\n- Risk assessment\n- Value realization review\n- Expansion opportunities\n- Executive alignment plan\n- Renewal timeline\n- Negotiation strategy\n- Pricing and packaging options",
    icon: TrendingUp,
    variables: ["customer", "date", "arr", "health"],
    tags: ["csm", "renewal", "expansion"],
  },
  {
    id: "sales-coaching",
    title: "Sales Coaching Session (Manager)",
    description: "Effective rep coaching framework",
    category: "sales",
    prompt: "Create a coaching plan for a sales rep struggling with {challenge}. Current metrics: {metrics}. Include:\n- Root cause analysis questions\n- Skill gaps to address\n- Practice scenarios/role-plays\n- Resource recommendations\n- 30-day improvement plan\n- Success criteria\n- Follow-up cadence",
    icon: Users,
    variables: ["challenge", "metrics"],
    tags: ["sales", "coaching", "management"],
  },
  {
    id: "qbr-presentation",
    title: "QBR Presentation (CSM)",
    description: "Quarterly business review deck",
    category: "sales",
    prompt: "Create a QBR presentation outline for {customer}. Include:\n- Slide 1: Agenda and goals\n- Slide 2: Success metrics and ROI achieved\n- Slide 3: Adoption and usage analytics\n- Slide 4: Key wins and case studies\n- Slide 5: Challenges and solutions\n- Slide 6: Roadmap and upcoming features\n- Slide 7: Growth opportunities\n- Slide 8: Next quarter goals\n- Slide 9: Action items",
    icon: Presentation,
    variables: ["customer"],
    tags: ["csm", "qbr", "presentation"],
  },

  // Creative Prompts
  {
    id: "brainstorm",
    title: "Brainstorm Ideas",
    description: "Generate creative ideas for any topic",
    category: "creative",
    prompt: "Help me brainstorm creative and innovative ideas for {topic}. Please provide at least 10 unique ideas with brief explanations for each.",
    icon: Lightbulb,
    variables: ["topic"],
    tags: ["ideas", "creative", "brainstorm"],
    featured: true,
  },
  {
    id: "story-gen",
    title: "Story Generator",
    description: "Create engaging stories with plot twists",
    category: "creative",
    prompt: "Write an engaging short story about {theme} with an unexpected plot twist. Include vivid descriptions and character development.",
    icon: BookOpen,
    variables: ["theme"],
    tags: ["story", "creative", "narrative"],
  },
  {
    id: "creative-names",
    title: "Name Generator",
    description: "Generate creative names for projects, products, or businesses",
    category: "creative",
    prompt: "Generate 20 creative and memorable names for a {type} related to {topic}. For each name, provide a brief explanation of its meaning and appeal.",
    icon: Sparkles,
    variables: ["type", "topic"],
    tags: ["naming", "branding", "creative"],
  },

  // Code Prompts
  {
    id: "debug-code",
    title: "Debug Code",
    description: "Find and fix bugs in your code",
    category: "code",
    prompt: "Please analyze this code and help me debug it:\n\n{code}\n\nIdentify any bugs, potential issues, or improvements. Provide the corrected code with explanations.",
    icon: Bug,
    variables: ["code"],
    tags: ["debug", "code", "fix"],
    featured: true,
  },
  {
    id: "code-review",
    title: "Code Review",
    description: "Get detailed code review with best practices",
    category: "code",
    prompt: "Review this code following best practices:\n\n{code}\n\nProvide feedback on:\n- Code quality and readability\n- Performance optimization\n- Security concerns\n- Design patterns\n- Suggested improvements",
    icon: GitBranch,
    variables: ["code"],
    tags: ["review", "code", "best-practices"],
  },
  {
    id: "explain-code",
    title: "Explain Code",
    description: "Get clear explanations of complex code",
    category: "code",
    prompt: "Explain this code in detail:\n\n{code}\n\nBreak down:\n- What it does\n- How it works\n- Key concepts used\n- Use cases",
    icon: Code,
    variables: ["code"],
    tags: ["explain", "code", "learning"],
  },
  {
    id: "optimize-code",
    title: "Optimize Performance",
    description: "Improve code performance and efficiency",
    category: "code",
    prompt: "Optimize this code for better performance:\n\n{code}\n\nFocus on:\n- Time complexity\n- Space complexity\n- Algorithm efficiency\n- Provide benchmarks if possible",
    icon: Rocket,
    variables: ["code"],
    tags: ["optimize", "performance", "code"],
    featured: true,
  },

  // Writing Prompts
  {
    id: "improve-writing",
    title: "Improve Writing",
    description: "Enhance clarity, tone, and impact",
    category: "writing",
    prompt: "Please improve this text:\n\n{text}\n\nEnhance:\n- Clarity and conciseness\n- Grammar and style\n- Tone and impact\n- Professional polish",
    icon: PenTool,
    variables: ["text"],
    tags: ["writing", "improve", "edit"],
    featured: true,
  },
  {
    id: "write-email",
    title: "Professional Email",
    description: "Compose professional emails",
    category: "writing",
    prompt: "Write a professional email about {topic} to {recipient}. The tone should be {tone}. Include a clear subject line.",
    icon: Mail,
    variables: ["topic", "recipient", "tone"],
    tags: ["email", "professional", "communication"],
  },
  {
    id: "summarize",
    title: "Summarize Content",
    description: "Create concise summaries",
    category: "writing",
    prompt: "Summarize the following content in {length} sentences:\n\n{content}\n\nHighlight the key points and main takeaways.",
    icon: FileText,
    variables: ["content", "length"],
    tags: ["summary", "concise", "tldr"],
  },

  // Analysis Prompts
  {
    id: "data-analysis",
    title: "Analyze Data",
    description: "Extract insights from data",
    category: "analysis",
    prompt: "Analyze this data and provide insights:\n\n{data}\n\nInclude:\n- Key patterns and trends\n- Statistical analysis\n- Visualizations (if applicable)\n- Actionable recommendations",
    icon: BarChart,
    variables: ["data"],
    tags: ["data", "analysis", "insights"],
    featured: true,
  },
  {
    id: "competitive-analysis",
    title: "Competitive Analysis",
    description: "Analyze competitors and market position",
    category: "analysis",
    prompt: "Provide a competitive analysis for {company/product} in the {industry} market. Include:\n- Key competitors\n- Strengths and weaknesses\n- Market positioning\n- Opportunities and threats\n- Strategic recommendations",
    icon: TrendingUp,
    variables: ["company/product", "industry"],
    tags: ["competitive", "market", "strategy"],
  },
  {
    id: "pros-cons",
    title: "Pros & Cons",
    description: "Balanced evaluation of options",
    category: "analysis",
    prompt: "Provide a detailed pros and cons analysis of {topic}. Be objective and comprehensive. Include potential risks and opportunities.",
    icon: CheckCircle,
    variables: ["topic"],
    tags: ["decision", "evaluation", "analysis"],
  },

  // Research Prompts
  {
    id: "research-topic",
    title: "Research Assistant",
    description: "Comprehensive research on any topic",
    category: "research",
    prompt: "Research {topic} and provide:\n- Overview and background\n- Key facts and statistics\n- Current trends and developments\n- Expert perspectives\n- Reliable sources and citations",
    icon: Search,
    variables: ["topic"],
    tags: ["research", "facts", "sources"],
    featured: true,
  },
  {
    id: "explain-concept",
    title: "Explain Like I'm 5",
    description: "Simple explanations of complex topics",
    category: "research",
    prompt: "Explain {concept} in simple terms that anyone can understand. Use analogies and examples. Avoid jargon.",
    icon: Brain,
    variables: ["concept"],
    tags: ["explain", "simple", "eli5"],
  },
  {
    id: "compare-concepts",
    title: "Compare & Contrast",
    description: "Compare different concepts or options",
    category: "research",
    prompt: "Compare and contrast {item1} vs {item2}. Include:\n- Similarities and differences\n- Use cases for each\n- Recommendations on which to choose\n- Visual comparison table",
    icon: Database,
    variables: ["item1", "item2"],
    tags: ["compare", "contrast", "decision"],
  },

  // Business Prompts
  {
    id: "business-plan",
    title: "Business Plan",
    description: "Create comprehensive business plans",
    category: "business",
    prompt: "Create a business plan for {business_idea}. Include:\n- Executive summary\n- Market analysis\n- Target audience\n- Revenue model\n- Marketing strategy\n- Financial projections\n- Risks and mitigation",
    icon: Briefcase,
    variables: ["business_idea"],
    tags: ["business", "plan", "startup"],
  },
  {
    id: "marketing-strategy",
    title: "Marketing Strategy",
    description: "Develop marketing campaigns",
    category: "business",
    prompt: "Develop a marketing strategy for {product/service} targeting {audience}. Include:\n- Key messaging\n- Channel strategy\n- Content ideas\n- Success metrics\n- Budget recommendations",
    icon: Target,
    variables: ["product/service", "audience"],
    tags: ["marketing", "strategy", "campaign"],
    featured: true,
  },

  // Customer Support Prompts
  {
    id: "support-response",
    title: "Customer Support Response",
    description: "Handle customer issues professionally",
    category: "support",
    prompt: "Create a customer support response for: {issue}. Customer sentiment: {sentiment}. Include:\n- Empathetic acknowledgment\n- Clear explanation\n- Step-by-step solution\n- Prevention tips\n- Follow-up plan\n- Escalation path if needed",
    icon: Headphones,
    variables: ["issue", "sentiment"],
    tags: ["support", "customer-service", "help"],
    featured: true,
  },
  {
    id: "kb-article",
    title: "Knowledge Base Article",
    description: "Create helpful KB articles",
    category: "support",
    prompt: "Write a knowledge base article for: {topic}. Include:\n- Clear title and summary\n- Problem statement\n- Step-by-step instructions with screenshots\n- Common pitfalls\n- Related articles\n- FAQ section\n- When to contact support",
    icon: BookOpen,
    variables: ["topic"],
    tags: ["support", "documentation", "kb"],
  },
  {
    id: "escalation-email",
    title: "Escalation Email",
    description: "Handle customer escalations",
    category: "support",
    prompt: "Draft an escalation email for {customer} regarding {issue}. Priority: {priority}. Include:\n- Sincere apology\n- Acknowledgment of impact\n- Root cause (if known)\n- Action plan with timeline\n- Compensation/goodwill gesture\n- Prevention measures\n- Executive contact info",
    icon: TrendingUp,
    variables: ["customer", "issue", "priority"],
    tags: ["support", "escalation", "crisis"],
  },

  // HR & People Operations Prompts
  {
    id: "job-description",
    title: "Job Description",
    description: "Create compelling job postings",
    category: "hr",
    prompt: "Write a job description for {role} at {company}. Experience level: {level}. Include:\n- Compelling company intro\n- Role overview and impact\n- Key responsibilities (5-7)\n- Must-have qualifications\n- Nice-to-have skills\n- Compensation range\n- Benefits and perks\n- DEI statement\n- Application process",
    icon: Users,
    variables: ["role", "company", "level"],
    tags: ["hr", "recruiting", "jd"],
    featured: true,
  },
  {
    id: "interview-questions",
    title: "Interview Questions",
    description: "Structured interview frameworks",
    category: "hr",
    prompt: "Create interview questions for hiring a {role}. Include:\n- 5 behavioral questions (STAR method)\n- 5 technical/skills questions\n- 3 culture-fit questions\n- 2 situational judgment scenarios\n- Red flags to watch for\n- Scoring rubric\n- Follow-up probes",
    icon: MessageSquare,
    variables: ["role"],
    tags: ["hr", "interview", "hiring"],
  },
  {
    id: "performance-review",
    title: "Performance Review",
    description: "Constructive performance feedback",
    category: "hr",
    prompt: "Write a performance review for {employee_name} - {role}. Performance: {rating}. Include:\n- Summary of period\n- Key accomplishments\n- Areas of strength\n- Growth opportunities\n- Specific examples (SBI framework)\n- Development plan\n- Goals for next period\n- Raise/promotion recommendation",
    icon: Award,
    variables: ["employee_name", "role", "rating"],
    tags: ["hr", "performance", "feedback"],
  },
  {
    id: "offer-letter",
    title: "Offer Letter",
    description: "Professional offer letters",
    category: "hr",
    prompt: "Draft an offer letter for {candidate} for {role}. Salary: {salary}. Include:\n- Warm welcome\n- Position details and start date\n- Compensation breakdown\n- Benefits summary\n- Equity/stock options\n- PTO policy\n- Reporting structure\n- Contingencies (background check, etc.)\n- Accept-by date\n- Enthusiastic close",
    icon: FileText,
    variables: ["candidate", "role", "salary"],
    tags: ["hr", "offer", "hiring"],
  },

  // Learning Prompts
  {
    id: "study-guide",
    title: "Study Guide",
    description: "Create comprehensive study materials",
    category: "learning",
    prompt: "Create a comprehensive study guide for {subject}. Include:\n- Key concepts and definitions\n- Important formulas or principles\n- Practice questions\n- Study tips\n- Additional resources",
    icon: BookOpen,
    variables: ["subject"],
    tags: ["study", "learning", "education"],
  },
  {
    id: "lesson-plan",
    title: "Lesson Plan",
    description: "Design engaging lessons",
    category: "learning",
    prompt: "Create a lesson plan to teach {topic} to {audience}. Include:\n- Learning objectives\n- Materials needed\n- Step-by-step activities\n- Assessment methods\n- Differentiation strategies",
    icon: BookOpen,
    variables: ["topic", "audience"],
    tags: ["teaching", "lesson", "education"],
  },

  // Productivity Prompts
  {
    id: "todo-organize",
    title: "Task Organizer",
    description: "Organize and prioritize tasks",
    category: "productivity",
    prompt: "Help me organize these tasks:\n\n{tasks}\n\nPrioritize using the Eisenhower Matrix (Urgent/Important). Provide a structured plan with time estimates.",
    icon: CheckCircle,
    variables: ["tasks"],
    tags: ["productivity", "organize", "tasks"],
  },
  {
    id: "meeting-agenda",
    title: "Meeting Agenda",
    description: "Create effective meeting agendas",
    category: "productivity",
    prompt: "Create a meeting agenda for {meeting_topic} with {participants}. Include:\n- Objectives\n- Time allocations\n- Discussion points\n- Action items template\n- Success criteria",
    icon: MessageSquare,
    variables: ["meeting_topic", "participants"],
    tags: ["meeting", "agenda", "productivity"],
  },

  // Translation & Language
  {
    id: "translate",
    title: "Translate Text",
    description: "Accurate translation with context",
    category: "writing",
    prompt: "Translate this text from {source_lang} to {target_lang}:\n\n{text}\n\nMaintain tone, context, and cultural nuances. Provide both literal and natural translations if different.",
    icon: Languages,
    variables: ["source_lang", "target_lang", "text"],
    tags: ["translate", "language", "localization"],
  },
];

export const quickActions = [
  {
    id: "summarize",
    label: "Summarize",
    icon: FileText,
    prompt: "Please summarize the following text concisely:\n\n{selection}",
  },
  {
    id: "explain",
    label: "Explain",
    icon: Brain,
    prompt: "Explain this in simple terms:\n\n{selection}",
  },
  {
    id: "improve",
    label: "Improve",
    icon: Sparkles,
    prompt: "Improve this text for clarity and impact:\n\n{selection}",
  },
  {
    id: "translate",
    label: "Translate",
    icon: Languages,
    prompt: "Translate this to {language}:\n\n{selection}",
  },
  {
    id: "expand",
    label: "Expand",
    icon: TrendingUp,
    prompt: "Expand on this topic with more detail:\n\n{selection}",
  },
];
