import Link from "next/link";
import { ArrowRight, Check, ShieldCheck } from "lucide-react";
import { SiteNav } from "@/components/next-site/SiteNav";
import { SiteFooter } from "@/components/next-site/SiteFooter";
import { PackageCheckoutButton } from "@/components/packages/PackageCheckoutButton";

export const metadata={title:"Start — Perpetual Core",description:"Buy software access, guided setup, a first workflow, or reserve a 90-day operating lane with Perpetual Core."};

const offers=[
  {id:"software-access" as const,n:"01",name:"SOFTWARE ACCESS",price:"$299",unit:"/ month",tag:"USE ONE SYSTEM",color:"#f3f1ea",ink:"#12151c",body:"Start with one focused Perpetual Core product surface and a clean path into implementation.",fit:"Best when the workflow is already understood and your team can configure its own context.",includes:["One product surface","Basic onboarding","Email support","Cancel before the next renewal"]},
  {id:"guided-setup" as const,n:"02",name:"GUIDED SETUP",price:"$2,500",unit:"one time",tag:"CONFIGURE IT RIGHT",color:"#d7ff3f",ink:"#12151c",body:"We configure the first system, import starter context, and establish the first operating rhythm.",fit:"Best for a small team that wants help starting without commissioning a custom build.",includes:["One intake call","System setup and context import","One workflow template","30-day check-in"]},
  {id:"first-workflow" as const,n:"03",name:"FIRST WORKFLOW",price:"$7,500",unit:"one time",tag:"SHIP THE FIRST LOOP",color:"#2457ff",ink:"white",body:"Map one costly handoff, connect the right system, and put a working operating loop into use.",fit:"Best when one recurring failure is already costing time, revenue, quality, or visibility.",includes:["Workflow and authority map","Product configuration","Light automation or template build","Success measure and next-step decision"]},
  {id:"operating-lane-deposit" as const,n:"04",name:"90-DAY LANE",price:"$5,000",unit:"reservation deposit",tag:"OPERATE IT WITH US",color:"#ff6338",ink:"#12151c",body:"Reserve a managed operating lane in capture, knowledge, people, diligence, or executive operations.",fit:"Best when you want Perpetual Core in the weekly operating rhythm—not merely providing software.",includes:["Reserved discovery capacity","Named operating lane","Weekly operating cadence","Month-three expand, renew, or handoff decision"]},
];

export default function PackagesPage({searchParams}:{searchParams?:{lead?:string}}){return <div className="min-h-screen bg-[#f3f1ea] text-[#12151c]"><SiteNav/><main id="main-content" className="pt-28">
  <section className="px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-[1500px]"><p className="text-[10px] font-black tracking-[.16em] text-[#2457ff]">BUY THE FIRST USEFUL THING / 01</p><div className="mt-7 grid gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><h1 className="max-w-5xl text-[clamp(3.8rem,7.5vw,7.5rem)] font-black leading-[.8] tracking-[-.075em]">START<br/>SMALL.<br/><span className="text-[#2457ff]">PROVE MORE.</span></h1><div className="border-l border-black/15 pl-8"><p className="text-2xl font-black leading-9">Choose the smallest purchase that can create operating evidence.</p><p className="mt-5 max-w-xl text-lg leading-8 text-[#5c626d]">Checkout is immediate. A human reviews every purchase before onboarding. Larger institutional work begins with scoped procurement.</p></div></div></div></section>

  <section className="bg-[#12151c] px-5 py-16 text-white sm:px-8 sm:py-24"><div className="mx-auto max-w-[1500px]"><div className="grid gap-4 lg:grid-cols-2">{offers.map(o=><article key={o.id} className="flex min-h-[540px] flex-col rounded-[28px] p-7 sm:p-9" style={{backgroundColor:o.color,color:o.ink}}><div className="flex items-start justify-between"><span className="text-xs font-black opacity-45">{o.n}</span><span className="rounded-full border border-current/20 px-3 py-2 text-[9px] font-black tracking-[.14em]">{o.tag}</span></div><h2 className="mt-14 text-4xl font-black tracking-[-.055em] sm:text-5xl">{o.name}</h2><div className="mt-4 flex items-end gap-3"><span className="text-4xl font-black tracking-[-.05em] sm:text-6xl">{o.price}</span><span className="pb-2 text-xs font-black uppercase tracking-[.12em] opacity-55">{o.unit}</span></div><p className="mt-7 max-w-xl text-lg font-bold leading-8">{o.body}</p><p className="mt-3 max-w-xl text-sm leading-6 opacity-65">{o.fit}</p><ul className="mt-7 grid gap-3 sm:grid-cols-2">{o.includes.map(item=><li key={item} className="flex gap-2 text-sm font-semibold"><Check className="mt-0.5 h-4 w-4 shrink-0"/>{item}</li>)}</ul><div className="mt-auto pt-9 [&_button]:min-h-14 [&_button]:w-full [&_button]:rounded-2xl [&_button]:bg-[#12151c] [&_button]:font-black [&_button]:text-white [&_button]:hover:bg-[#2b303b]"><PackageCheckoutButton packageId={o.id} leadId={searchParams?.lead}>Buy {o.name.toLowerCase()}</PackageCheckoutButton></div></article>)}</div></div></section>

  <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-black tracking-[.16em] text-[#2457ff]">WHAT HAPPENS AFTER PAYMENT / 02</p><h2 className="mt-6 text-5xl font-black leading-[.9] tracking-[-.06em]">PAYMENT IS NOT AUTOMATIC APPROVAL.</h2></div><div className="divide-y divide-black/10 border-y border-black/10">{[["01","Receipt + review","Stripe confirms payment. A human reviews the purchase and operating fit."],["02","Bounded intake","You provide the company, workflow, data-boundary, and success context needed to begin."],["03","Start decision","We confirm onboarding, scope boundaries, and the exact operating start. If the purchase is not a responsible fit, we resolve it directly."]].map(([n,t,b])=><div key={n} className="grid gap-4 py-7 sm:grid-cols-[60px_180px_1fr]"><span className="text-xs font-black text-black/35">{n}</span><h3 className="font-black">{t}</h3><p className="text-sm leading-6 text-[#626873]">{b}</p></div>)}</div></div></section>

  <section className="bg-[#2457ff] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="mx-auto flex max-w-[1500px] flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black tracking-[.15em] text-[#d7ff3f]"><ShieldCheck className="h-4 w-4"/> PROCUREMENT / ENTERPRISE</div><h2 className="mt-5 max-w-5xl text-4xl font-black leading-[.92] tracking-[-.055em] sm:text-6xl">NEED A CUSTOM SCOPE, ACH, OR INSTITUTIONAL AGREEMENT?</h2></div><Link href="/contact-sales?intent=manual-invoice" className="inline-flex min-h-14 shrink-0 items-center justify-center rounded-2xl bg-white px-6 font-black text-[#12151c]">Open procurement conversation <ArrowRight className="ml-3 h-5 w-5"/></Link></div></section>
  </main><SiteFooter/></div>}
