import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { SiteNav } from "@/components/next-site/SiteNav";
import { SiteFooter } from "@/components/next-site/SiteFooter";

const moves = [["01","TRACE","Find the decision, handoff, and evidence that actually govern the work."],["02","INSTALL","Build the smallest governed system that changes operating behavior."],["03","PROVE","Run it against an explicit decision: expand, revise, productize, or stop."]];
export const metadata = { title: "Studio — Perpetual Core", description: "A governed systems studio for consequential institutional workflows." };
export default function StudioPage(){return <div className="min-h-screen bg-[#f3f1ea] text-[#12151c]"><SiteNav/><main className="pt-28">
  <section className="px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-[1500px]"><div className="grid gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-[10px] font-black tracking-[.16em] text-[#2457ff]">PERPETUAL STUDIO / BUILD MODE</p><h1 className="mt-7 text-[clamp(3.75rem,7.2vw,7.25rem)] font-black leading-[.82] tracking-[-.075em]">DON&apos;T BUY<br/>AN AI<br/><span className="text-[#2457ff]">THEATER.</span></h1></div><div className="flex flex-col justify-end border-l border-black/10 pl-8"><p className="text-2xl font-bold leading-9">Bring us one workflow where the cost of fragmentation is visible.</p><p className="mt-5 text-lg leading-8 text-[#5d626d]">We map the operating reality, install the smallest useful system, and make the next investment decision legible.</p><Link href="/contact-sales" className="mt-8 inline-flex min-h-14 items-center justify-center self-start rounded-2xl bg-[#12151c] px-6 font-black text-white">Start with the broken handoff <ArrowRight className="ml-3 h-5 w-5"/></Link></div></div></div></section>
  <section className="bg-[#12151c] px-5 py-20 text-white sm:px-8 sm:py-24"><div className="mx-auto max-w-[1500px]"><p className="text-[10px] font-black tracking-[.16em] text-[#d7ff3f]">THE BUILD SEQUENCE</p><div className="mt-12 grid border-y border-white/10 lg:grid-cols-3">{moves.map(([n,t,b],i)=><div key={n} className={`min-h-[360px] py-8 lg:p-9 ${i<2?"lg:border-r lg:border-white/10":""}`}><span className="text-xs font-black text-white/25">{n}</span><h2 className="mt-20 text-5xl font-black tracking-[-.055em]" style={{color:i===0?"#d7ff3f":i===1?"#ff6338":"#ffffff"}}>{t}</h2><p className="mt-6 max-w-sm text-lg leading-8 text-white/55">{b}</p></div>)}</div></div></section>
  <section className="bg-[#d7ff3f] px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-2"><h2 className="text-5xl font-black leading-[.9] tracking-[-.06em] sm:text-7xl">A PILOT IS A DECISION INSTRUMENT.</h2><div className="text-lg font-semibold leading-8"><p>It needs an owner, a bounded workflow, a baseline, protected-data rules, and an explicit decision date.</p><p className="mt-5">If those do not exist, we help establish them before software becomes the distraction.</p></div></div></section>
  </main><SiteFooter/></div>}
