import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { SiteNav } from "@/components/next-site/SiteNav";
import { SiteFooter } from "@/components/next-site/SiteFooter";

const moves = [["01","TRACE","Find the decision, handoff, and evidence that actually govern the work."],["02","INSTALL","Build the smallest governed system that changes operating behavior."],["03","PROVE","Run it against an explicit decision: expand, revise, productize, or stop."]];
export const metadata = { title: "Studio — Perpetual Core", description: "A governed systems studio for consequential institutional workflows." };
export default function StudioPage(){return <div className="min-h-screen bg-[#f3f1ea] text-[#12151c]"><SiteNav/><main id="main-content" className="pt-28">
  <section className="px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-[1500px]"><div className="grid gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-[10px] font-black tracking-[.16em] text-[#2457ff]">PERPETUAL STUDIO / SCOPED IMPLEMENTATION</p><h1 className="mt-7 text-[clamp(3.5rem,6.8vw,6.9rem)] font-black leading-[.84] tracking-[-.072em]">FIX ONE WORKFLOW THAT KEEPS <span className="text-[#2457ff]">BREAKING.</span></h1></div><div className="flex flex-col justify-end border-l-2 border-[#2457ff] pl-6 sm:pl-8"><p className="text-2xl font-bold leading-9">The Studio turns one costly handoff into a working, governed operating loop.</p><p className="mt-5 text-lg leading-8 text-[#5d626d]">You leave with a mapped workflow, configured system, authority boundaries, and evidence for the next investment decision—not a strategy deck that stops at recommendations.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/packages" className="inline-flex min-h-14 items-center justify-center rounded-2xl bg-[#12151c] px-6 font-black text-white">See scope and pricing <ArrowRight className="ml-3 h-5 w-5"/></Link><Link href="/contact-sales" className="inline-flex min-h-14 items-center justify-center rounded-2xl border border-black/15 px-6 font-black hover:bg-white">Discuss a custom build</Link></div></div></div></div></section>
  <section className="border-y border-black/10 bg-white/45 px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-[10px] font-black tracking-[.16em] text-[#2457ff]">WHAT YOU RECEIVE</p><h2 className="mt-4 text-4xl font-black leading-[.95] tracking-[-.05em]">A working first loop with a decision attached.</h2></div><div className="grid gap-3 sm:grid-cols-2">{["Current-state workflow and ownership map","Configured product or operating surface","Human approval and protected-data boundaries","Success measure and expansion decision","Implementation notes and handoff plan","Clear exclusions, dependencies, and next steps"].map(item=><div key={item} className="flex min-h-20 items-start gap-3 rounded-2xl border border-black/10 bg-[#f3f1ea] p-5"><Check aria-hidden="true" className="mt-0.5 h-5 w-5 shrink-0 text-[#2457ff]"/><span className="text-sm font-bold leading-6">{item}</span></div>)}</div></div></section>
  <section className="bg-[#12151c] px-5 py-20 text-white sm:px-8 sm:py-24"><div className="mx-auto max-w-[1500px]"><p className="text-[10px] font-black tracking-[.16em] text-[#d7ff3f]">THE BUILD SEQUENCE</p><div className="mt-12 grid border-y border-white/10 lg:grid-cols-3">{moves.map(([n,t,b],i)=><div key={n} className={`min-h-[360px] py-8 lg:p-9 ${i<2?"lg:border-r lg:border-white/10":""}`}><span className="text-xs font-black text-white/25">{n}</span><h2 className="mt-20 text-5xl font-black tracking-[-.055em]" style={{color:i===0?"#d7ff3f":i===1?"#ff6338":"#ffffff"}}>{t}</h2><p className="mt-6 max-w-sm text-lg leading-8 text-white/55">{b}</p></div>)}</div></div></section>
  <section className="bg-[#d7ff3f] px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-2"><h2 className="text-5xl font-black leading-[.9] tracking-[-.06em] sm:text-7xl">A PILOT IS A DECISION INSTRUMENT.</h2><div className="text-lg font-semibold leading-8"><p>It needs an owner, a bounded workflow, a baseline, protected-data rules, and an explicit decision date.</p><p className="mt-5">If those do not exist, we help establish them before software becomes the distraction.</p></div></div></section>
  </main><SiteFooter/></div>}
