import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, CircleDollarSign, Clock3, ShieldCheck } from "lucide-react";
import { SiteNav } from "@/components/next-site/SiteNav";
import { SiteFooter } from "@/components/next-site/SiteFooter";
import { OfferPathfinder } from "@/components/offers/OfferPathfinder";
import { Reveal } from "@/components/next-site/Reveal";

export const metadata: Metadata = { title: "Ways to Start — Perpetual Core", description: "Map the first AI operating investment, install one bounded production workflow, or establish a managed operating lane." };

const offers = [
  { index: "01", name: "OPERATING SYSTEM MAP", price: "$7.5K–$15K", duration: "1–2 WEEKS", color: "#d7ff3f", ink: "#12151c", buyer: "You know the operation carries too much disconnected work, but the first investment is not yet obvious.", promise: "Choose the first workflow with its economics, authority boundaries, implementation range, and decision-ready 90-day sequence visible.", deliverables: ["Executive and operator discovery", "Current-state workflow and system map", "Friction, risk, and value analysis", "Prioritized first-workflow specification", "Implementation range and 90-day sequence"], cta: "Request the map", href: "/contact-sales?plan=guided-setup&intent=operating-system-map", pdf: "/downloads/offers/perpetual-core-operating-system-map.pdf", note: "The Map is the default starting point when workflow clarity, economics, or authority boundaries still need resolution." },
  { index: "02", name: "WORKFLOW PROOF SPRINT", price: "$30K–$75K", duration: "4–8 WEEKS", color: "#2457ff", ink: "white", buyer: "One recurring workflow is already costing time, revenue, quality, or visibility—and it has a named operating owner.", promise: "Install one bounded production workflow with explicit approval gates, operator training, and an agreed proof-of-value review.", deliverables: ["Signed workflow specification and measures", "Configured or custom production workflow", "Integration, permission, and authority boundaries", "Operator training and runbook", "Launch evidence and outcome-review plan"], cta: "Scope the sprint", href: "/contact-sales?plan=studio-sprint-30&intent=workflow-proof-sprint", pdf: "/downloads/offers/perpetual-core-workflow-proof-sprint.pdf", note: "Scope and acceptance criteria are agreed before build. Outcomes affected by adoption, customers, or third parties are measured—not guaranteed." },
  { index: "03", name: "MANAGED OPERATING LANE", price: "$10K–$35K/MO", duration: "90-DAY INITIAL TERM", color: "#ff6338", ink: "#12151c", buyer: "The workflow is strategically important and needs ongoing operating capacity—not another handoff after launch.", promise: "Operate and improve a named lane with explicit capacity, service boundaries, approval rules, exception reporting, and monthly decisions.", deliverables: ["Named lane, capacity, and service boundaries", "Monthly operating cadence and queue", "Human approval and escalation rules", "Evidence and exception reporting", "Monthly performance and expansion review"], cta: "Design the lane", href: "/contact-sales?plan=operating-lane-deposit&intent=managed-operating-lane", pdf: "/downloads/offers/perpetual-core-managed-operating-lane.pdf", note: "Renewal and expansion require explicit agreement. The initial term creates enough time to establish an honest operating baseline." },
] as const;

const principles = [
  { icon: Clock3, title: "Fast first decision", body: "Know what is being bought, who owns it, and how it will be judged before work begins." },
  { icon: ShieldCheck, title: "Human authority stays explicit", body: "Consequential actions, professional judgment, and official systems remain under named human authority." },
  { icon: CircleDollarSign, title: "Expansion follows evidence", body: "A Map can become a Sprint; a proven workflow can become a Managed Lane through a new written scope." },
] as const;

export default function OffersPage() {
  return <div className="min-h-screen bg-[#f3f1ea] text-[#12151c]"><SiteNav /><main id="main-content" className="pt-24">
    <section className="px-5 pb-16 pt-16 sm:px-8 sm:pb-24 sm:pt-24"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-end">
      <Reveal><p className="text-[10px] font-black tracking-[.16em] text-[#2457ff]">COMMERCIAL ARCHITECTURE / START NARROW</p><h1 className="mt-7 max-w-5xl text-[clamp(3.7rem,7.4vw,7.4rem)] font-black leading-[.81] tracking-[-.075em]">BUY THE NEXT <span className="text-[#2457ff]">OPERATING RESULT.</span></h1></Reveal>
      <Reveal className="border-l border-black/15 pl-7 sm:pl-9"><p className="text-2xl font-black leading-9">Not a vague AI transformation. Not an open-ended consulting engagement.</p><p className="mt-5 max-w-xl text-lg leading-8 text-[#5c626d]">Every engagement begins with a named workflow, owner, authority boundary, and evidence plan. Choose the smallest offer that can prove the next investment.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="#pathfinder" className="inline-flex min-h-14 items-center justify-center rounded-xl bg-[#12151c] px-6 text-sm font-black text-white hover:bg-[#2b303b]">Find my starting point <ArrowRight className="ml-2 h-4 w-4" /></Link><Link href="/legal" className="inline-flex min-h-14 items-center justify-center rounded-xl border border-black/15 px-6 text-sm font-black hover:bg-white/60">Review terms</Link></div></Reveal>
    </div></section>

    <section className="bg-[#12151c] px-5 py-16 text-white sm:px-8 sm:py-24"><div className="mx-auto max-w-[1500px]"><div className="grid gap-4 lg:grid-cols-3">{offers.map((offer) => <article key={offer.name} className="flex min-h-[650px] flex-col rounded-[26px] p-6 sm:p-8" style={{backgroundColor:offer.color,color:offer.ink}}><div className="flex items-center justify-between"><span className="text-xs font-black opacity-45">{offer.index}</span><span className="rounded-full border border-current/20 px-3 py-2 text-[9px] font-black tracking-[.13em]">{offer.duration}</span></div><h2 className="mt-12 text-4xl font-black leading-[.9] tracking-[-.055em]">{offer.name}</h2><p className="mt-5 text-3xl font-black tracking-[-.04em]">{offer.price}</p><p className="mt-7 text-sm font-bold leading-6"><span className="opacity-55">BEST WHEN / </span>{offer.buyer}</p><p className="mt-5 text-base font-semibold leading-7 opacity-75">{offer.promise}</p><ul className="mt-7 space-y-3">{offer.deliverables.map(item=><li key={item} className="flex gap-2 text-sm font-semibold leading-5"><Check className="mt-0.5 h-4 w-4 shrink-0" />{item}</li>)}</ul><div className="mt-auto pt-8"><Link href={offer.href} className="inline-flex min-h-14 w-full items-center justify-center rounded-xl bg-[#12151c] px-5 text-sm font-black text-white transition-colors hover:bg-white hover:text-[#12151c] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/50">{offer.cta}<ArrowRight className="ml-2 h-4 w-4" /></Link><a href={offer.pdf} download className="mt-2 inline-flex min-h-12 w-full items-center justify-center rounded-xl border border-current/20 px-5 text-xs font-black transition-colors hover:bg-white/25 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/50">Download one-page PDF</a><p className="mt-4 text-xs leading-5 opacity-60">{offer.note}</p></div></article>)}</div></div></section>

    <section id="pathfinder" className="scroll-mt-24 bg-[#12151c] px-5 pb-20 text-white sm:px-8 sm:pb-28"><div className="mx-auto max-w-[1500px] border-t border-white/12 pt-16 sm:pt-20"><div className="mb-12 grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><p className="text-[10px] font-black tracking-[.16em] text-[#d7ff3f]">OFFER PATHFINDER / 01</p><div><h2 className="text-4xl font-black leading-[.94] tracking-[-.055em] sm:text-6xl">NOT SURE WHERE TO START?</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/58">Use three operating questions to narrow the fit. The recommendation opens a tailored intake; it does not approve or bind either party.</p></div></div><OfferPathfinder /></div></section>

    <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-[1500px] gap-4 lg:grid-cols-3">{principles.map(({icon:FeatureIcon,title,body})=><div key={title} className="rounded-[22px] border border-black/10 bg-white/55 p-7"><FeatureIcon className="h-5 w-5 text-[#2457ff]"/><h2 className="mt-6 text-xl font-black">{title}</h2><p className="mt-3 text-sm leading-6 text-[#626873]">{body}</p></div>)}</div></section>

    <section className="bg-[#d7ff3f] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto flex max-w-[1500px] flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black tracking-[.16em]">WHEN IN DOUBT / START HERE</p><h2 className="mt-5 max-w-5xl text-4xl font-black leading-[.92] tracking-[-.055em] sm:text-6xl">MAP THE COMPANY BEFORE YOU BUY THE BUILD.</h2></div><Link href="/contact-sales?plan=guided-setup&intent=operating-system-map" className="inline-flex min-h-14 shrink-0 items-center justify-center rounded-xl bg-[#12151c] px-6 text-sm font-black text-white hover:bg-[#2b303b]">Request the map <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section>
  </main><SiteFooter /></div>;
}
