import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, CircleDollarSign, Clock3, ShieldCheck } from "lucide-react";
import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import { SkipLink } from "@/components/ui/accessibility";

export const metadata: Metadata = { title: "Engagements & Offers", description: "Start with a paid operating-system map, install one measurable workflow, or retain a managed operating lane." };

const offers = [
  { index: "01", name: "Operating System Map", price: "$7.5K–$15K", duration: "1–2 weeks", buyer: "You know the company is carrying too much manual work, but the first investment is not yet obvious.", promise: "Leave with a decision-ready map of the first workflow, its economics, authority boundaries, implementation scope, and 90-day sequence.", deliverables: ["Executive and operator discovery", "Current-state workflow and system map", "Friction, risk, and value analysis", "Prioritized first-workflow specification", "Implementation range and 90-day roadmap"], cta: "Book the map", href: "/contact-sales?plan=guided-setup&intent=operating-system-map", note: "If a Studio Sprint starts within 30 days, up to 50% of the Map fee may be credited in the signed SOW." },
  { index: "02", name: "Workflow Proof Sprint", price: "$30K–$75K", duration: "4–8 weeks", buyer: "One recurring workflow is already costing time, revenue, quality, or visibility—and leadership wants production evidence.", promise: "Install one bounded workflow with an owner, system-of-record boundaries, approval gates, operator training, and an agreed proof-of-value review.", deliverables: ["Signed workflow specification and success measures", "Configured or custom production workflow", "Integration and permission boundaries", "Operator training and runbook", "Launch evidence and outcome-review plan"], cta: "Scope the sprint", href: "/contact-sales?plan=studio-sprint-30&intent=workflow-proof-sprint", note: "Scope and acceptance criteria are agreed before build. We do not guarantee business outcomes that depend on adoption, customer behavior, or third parties." },
  { index: "03", name: "Managed Operating Lane", price: "$10K–$35K/mo", duration: "90-day initial term", buyer: "The workflow is strategically important and needs a named operating rhythm—not another handoff after launch.", promise: "Perpetual Core operates and improves a defined lane with your team: capture, knowledge, people, diligence, or executive operations.", deliverables: ["Named lane, capacity, and service boundaries", "Monthly operating cadence and queue", "Human approval and escalation rules", "Evidence and exception reporting", "Monthly performance and expansion review"], cta: "Design the lane", href: "/contact-sales?plan=operating-lane-deposit&intent=managed-operating-lane", note: "The initial term establishes a fair evaluation window. Renewal and expansion require explicit agreement; there is no invented scarcity or automatic outcome claim." },
] as const;

export default function OffersPage() { return <div className="min-h-screen bg-[#f7f6f2] text-[#17171b]"><SkipLink /><Navbar /><main id="main-content">
  <section className="mx-auto max-w-[1440px] px-5 pb-16 pt-20 sm:px-8 sm:pb-24 sm:pt-28"><p className="font-mono text-[11px] uppercase tracking-[0.18em] text-[#5146c7]">Commercial architecture / start narrow / expand on proof</p><h1 className="mt-7 max-w-5xl text-5xl font-semibold leading-[0.95] tracking-[-0.055em] sm:text-7xl lg:text-[88px]">Buy the next operating result—not a vague AI transformation.</h1><p className="mt-8 max-w-3xl text-lg leading-8 text-[#5a5a63] sm:text-xl">Every engagement begins with a named workflow, owner, authority boundary, and evidence plan. Choose the smallest offer that can prove the next investment.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="#offers" className="inline-flex min-h-12 items-center bg-[#17171b] px-6 text-sm font-semibold text-white hover:bg-[#5146c7] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#5146c7]/40">Compare offers <ArrowRight className="ml-2 h-4 w-4" aria-hidden="true" /></Link><Link href="/legal" className="inline-flex min-h-12 items-center border border-black/20 px-6 text-sm font-semibold hover:border-[#5146c7] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#5146c7]/40">Review contracting terms</Link></div></section>
  <section id="offers" className="scroll-mt-24 border-t border-black/10"><div className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 sm:py-24"><div className="space-y-6">{offers.map((offer) => <article key={offer.name} className="grid gap-8 border border-black/12 bg-white p-6 sm:p-9 lg:grid-cols-[100px_1.2fr_1fr]"><div><span className="font-mono text-xs text-[#5146c7]">{offer.index}</span></div><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#676771]">{offer.duration}</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.035em] sm:text-5xl">{offer.name}</h2><p className="mt-4 text-3xl font-semibold text-[#5146c7]">{offer.price}</p><p className="mt-6 text-sm leading-6 text-[#5c5c65]"><strong className="text-[#202025]">Best when:</strong> {offer.buyer}</p><p className="mt-4 text-base leading-7 text-[#34343b]">{offer.promise}</p><Link href={offer.href} className="mt-7 inline-flex min-h-12 items-center bg-[#17171b] px-6 text-sm font-semibold text-white hover:bg-[#5146c7] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#5146c7]/40">{offer.cta} <ArrowRight className="ml-2 h-4 w-4" aria-hidden="true" /></Link></div><div><h3 className="text-xs font-semibold uppercase tracking-[0.14em]">Included</h3><ul className="mt-5 space-y-3">{offer.deliverables.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-[#505059]"><Check className="mt-1 h-4 w-4 shrink-0 text-[#5146c7]" aria-hidden="true" />{item}</li>)}</ul><p className="mt-7 border-l-2 border-[#5146c7] pl-4 text-xs leading-5 text-[#666670]">{offer.note}</p></div></article>)}</div></div></section>
  <section className="border-t border-black/10 bg-[#111116] text-white"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-16 sm:px-8 lg:grid-cols-3"><div className="border border-white/12 p-6"><Clock3 className="h-5 w-5 text-[#54e6b1]" aria-hidden="true" /><h2 className="mt-5 text-lg font-semibold">Fast first decision</h2><p className="mt-3 text-sm leading-6 text-white/62">You should know what is being bought, who owns it, and how it will be judged before work begins.</p></div><div className="border border-white/12 p-6"><ShieldCheck className="h-5 w-5 text-[#54e6b1]" aria-hidden="true" /><h2 className="mt-5 text-lg font-semibold">Human authority remains explicit</h2><p className="mt-3 text-sm leading-6 text-white/62">No autonomous promise silently overrides customer approvals, professional judgment, or official systems of record.</p></div><div className="border border-white/12 p-6"><CircleDollarSign className="h-5 w-5 text-[#54e6b1]" aria-hidden="true" /><h2 className="mt-5 text-lg font-semibold">Expansion follows evidence</h2><p className="mt-3 text-sm leading-6 text-white/62">A successful workflow can become a managed lane, department system, or broader Engine install through a new written scope.</p></div></div></section>
</main><Footer tone="dark" /></div>; }
