export type LegalSection = { heading: string; paragraphs?: readonly string[]; items?: readonly string[] };
export type LegalDocument = { title: string; description: string; effective: string; notice?: string; sections: readonly LegalSection[] };

const effective = "August 29, 2026";
const company = "THE PERPETUAL CORE LLC, a New York limited liability company";

export const privacyPolicy: LegalDocument = {
  title: "Privacy Policy",
  description: "How Perpetual Core collects, uses, discloses, retains, and protects information across its public sites, products, and services.",
  effective,
  sections: [
    { heading: "1. Scope and company", paragraphs: [`This Policy applies to ${company} (\"Perpetual Core,\" \"we,\" \"us,\" or \"our\") and the websites, products, applications, and professional services that link to it. A product-specific notice, signed agreement, or customer instruction may supplement or control over this Policy for a particular engagement.`] },
    { heading: "2. Information we collect", items: ["Contact and account information, including name, business email, role, organization, authentication records, and support communications.", "Customer content supplied to a product or engagement, including documents, prompts, workflow data, recordings, and instructions.", "Commercial information, including plan, contract, invoice, transaction status, and procurement records. Payment-card data is handled by the payment processor, not stored directly by Perpetual Core.", "Device and service data, including IP address, browser, timestamps, product events, diagnostics, security logs, and cookie choices.", "Public or licensed information used for research, opportunity discovery, or customer-authorized enrichment."] },
    { heading: "3. How we use information", items: ["Provide, secure, maintain, support, and improve the requested service.", "Authenticate users, enforce permissions, prevent abuse, and investigate incidents.", "Generate customer-requested analysis, drafts, recommendations, and workflow outputs.", "Process transactions and administer customer relationships.", "Comply with law, enforce agreements, and protect rights and safety.", "Send operational communications and, where permitted, marketing communications that recipients may opt out of."] },
    { heading: "4. AI processing", paragraphs: ["Some services send only the context needed for a requested task to configured AI providers. The applicable product, order form, or data-processing addendum should identify material processing terms. AI output can be incomplete or incorrect and must be reviewed before consequential use.", "We do not claim that every product or deployment has the same provider, retention setting, security configuration, or regulated-data authorization. Those facts are confirmed in writing for the applicable engagement."] },
    { heading: "5. Disclosure and subprocessors", items: ["Service providers that host, secure, analyze, communicate, or process payments for the service.", "Customer-authorized integrations and collaborators.", "Professional advisers and authorities when reasonably necessary for legal, security, or compliance purposes.", "A successor in a merger, financing, reorganization, or sale, subject to appropriate protections."] },
    { heading: "6. Retention and deletion", paragraphs: ["We retain information for the period reasonably necessary to deliver the service, maintain security and business records, meet contractual requirements, and comply with law. Retention differs by product and data type. Customer contracts or product controls may provide more specific deletion and export commitments."] },
    { heading: "7. Security", paragraphs: ["We use administrative, technical, and physical safeguards appropriate to the nature of the service and information. No system is perfectly secure. Security claims on a product page or customer security exhibit apply only where expressly stated and verified."] },
    { heading: "8. Regulated and sensitive data", paragraphs: ["Do not submit protected health information, student records, payment-card data, government identifiers, or other regulated data unless the applicable service and written agreement expressly authorize it. Perpetual Core does not act as a HIPAA business associate unless an authorized Business Associate Agreement is fully executed for the specific service."] },
    { heading: "9. Your choices and requests", paragraphs: ["Depending on applicable law and the relationship, individuals may request access, correction, deletion, restriction, or a copy of certain personal information. We may need to verify identity and may retain information where law or a contract permits. Send requests to info@perpetualcore.com with the subject line ‘Privacy request.’"] },
    { heading: "10. Children, international use, and changes", paragraphs: ["The general business services are not directed to children. A child- or student-facing service requires its own consent and privacy design. Information may be processed in the United States and other locations used by approved providers. We will post material Policy changes with a revised effective date."] },
    { heading: "11. Contact", paragraphs: ["Privacy, contract, or security questions: info@perpetualcore.com. Use a descriptive subject line so the request can be routed correctly. Mail: THE PERPETUAL CORE LLC, New York, United States."] },
  ],
};

export const termsOfService: LegalDocument = {
  title: "Terms of Service",
  description: "The baseline terms for use of Perpetual Core public websites and online services when no separately signed agreement controls.",
  effective,
  notice: "A signed Master Services Agreement, Order Form, Statement of Work, Data Processing Addendum, or other written agreement controls if it conflicts with these online terms.",
  sections: [
    { heading: "1. Agreement and eligibility", paragraphs: [`These Terms are between you and ${company}. If you use a service for an organization, you represent that you are authorized to bind that organization.`] },
    { heading: "2. Services and accounts", paragraphs: ["You must provide accurate information, protect account credentials, and promptly report suspected misuse. Features, limits, availability, and support are defined by the applicable product page, order, or statement of work. Beta, pilot, and evaluation features may change or end."] },
    { heading: "3. Customer responsibilities", items: ["Use the service lawfully and follow the Acceptable Use Policy.", "Obtain necessary rights, notices, permissions, and consents for customer content and connected systems.", "Review AI-assisted and automated outputs before relying on them, especially for legal, financial, employment, education, health, safety, eligibility, procurement, or other consequential decisions.", "Maintain appropriate backups and authoritative records unless a written agreement assigns that responsibility to Perpetual Core.", "Do not submit regulated data unless expressly authorized in writing for that service."] },
    { heading: "4. Fees, taxes, and renewals", paragraphs: ["Fees, deposits, milestones, usage charges, renewal terms, and taxes are stated at checkout or in an order. Unless the order says otherwise, fees are non-refundable once the applicable service period or work begins. Recurring services renew as disclosed until canceled under the applicable order."] },
    { heading: "5. Intellectual property", paragraphs: ["Perpetual Core and its licensors retain rights in the service, platform, methods, templates, pre-existing materials, and improvements. You retain rights in customer content. Project-specific ownership and license terms are stated in the applicable statement of work; no custom deliverable is transferred before full payment unless the statement of work says otherwise."] },
    { heading: "6. AI and third-party services", paragraphs: ["AI output is probabilistic and may contain errors, omissions, bias, or material that requires clearance. It is not professional advice or a substitute for qualified judgment. Integrations and third-party services remain subject to their own terms and availability."] },
    { heading: "7. Confidentiality and data", paragraphs: ["Each party must protect non-public information disclosed in circumstances indicating confidentiality and use it only for the relationship. The Privacy Policy governs personal information; an executed Data Processing Addendum or Business Associate Agreement controls where applicable."] },
    { heading: "8. Suspension and termination", paragraphs: ["We may suspend access when reasonably necessary to address security, unlawful use, nonpayment, material breach, or risk to the service or others. Either party may terminate as stated in the applicable order. Provisions that by nature should survive—including payment, confidentiality, intellectual property, disclaimers, limits, and dispute terms—survive."] },
    { heading: "9. Disclaimers", paragraphs: ["EXCEPT AS EXPRESSLY PROVIDED IN A SIGNED AGREEMENT, SERVICES ARE PROVIDED \"AS IS\" AND \"AS AVAILABLE.\" TO THE MAXIMUM EXTENT PERMITTED BY LAW, PERPETUAL CORE DISCLAIMS IMPLIED WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT GUARANTEE FUNDING, AWARDS, REVENUE, COMPLIANCE, EMPLOYMENT, PLACEMENT, HEALTH, OR OTHER OUTCOMES."] },
    { heading: "10. Limitation of liability", paragraphs: ["TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER PARTY IS LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES OR LOST PROFITS, REVENUE, DATA, OR GOODWILL. EXCEPT FOR AMOUNTS OWED, MISUSE OF INTELLECTUAL PROPERTY, BREACH OF CONFIDENTIALITY, OR LIABILITY THAT CANNOT LAWFULLY BE LIMITED, EACH PARTY'S AGGREGATE LIABILITY UNDER THESE TERMS WILL NOT EXCEED THE AMOUNT PAID OR PAYABLE FOR THE AFFECTED SERVICE DURING THE SIX MONTHS BEFORE THE EVENT GIVING RISE TO LIABILITY."] },
    { heading: "11. Governing law and disputes", paragraphs: ["New York law governs without regard to conflict-of-law rules. Before filing a claim, the parties will attempt in good faith to resolve it through written notice and an executive discussion. Unless a signed agreement provides otherwise, exclusive venue lies in the state or federal courts located in New York County, New York."] },
    { heading: "12. General and contact", paragraphs: ["Neither party may assign these Terms except in connection with a merger, reorganization, sale of substantially all assets, or with consent. Failure to enforce is not a waiver. If one provision is unenforceable, the remainder continues. Contact: info@perpetualcore.com."] },
  ],
};

export const acceptableUsePolicy: LegalDocument = { title: "Acceptable Use Policy", description: "Rules protecting customers, people, and systems that use Perpetual Core services.", effective, sections: [
  { heading: "Use services responsibly", paragraphs: ["You may not use a Perpetual Core service, or help another person use it, for prohibited activity."] },
  { heading: "Prohibited conduct", items: ["Illegal, fraudulent, deceptive, harassing, exploitative, or rights-infringing activity.", "Malware, credential theft, unauthorized surveillance, security testing without written permission, or interference with a service.", "High-impact decisions about employment, housing, credit, education, health, insurance, legal rights, or public benefits without authorized human review and required safeguards.", "Impersonation, undisclosed deceptive synthetic media, spam, or unlawful marketing.", "Collection or processing of protected or regulated data outside an expressly approved service and agreement.", "Attempts to bypass access controls, rate limits, safety measures, approval gates, or audit records.", "Using output as verified fact, professional advice, or an official record without appropriate review."] },
  { heading: "Enforcement and reporting", paragraphs: ["We may investigate suspected violations and restrict affected access when reasonably necessary. Report abuse or security concerns to info@perpetualcore.com with the subject line ‘Security report.’"] },
] };

export const aiDisclosure: LegalDocument = { title: "AI Use & Human Authority Disclosure", description: "Where Perpetual Core uses AI, what it can and cannot establish, and when a human must decide.", effective, sections: [
  { heading: "AI supports work; it does not inherit authority", paragraphs: ["Perpetual Core systems may retrieve information, summarize sources, generate drafts, classify material, recommend actions, or prepare work for approval. Output does not by itself create an official decision, commitment, filing, payment, diagnosis, legal conclusion, hiring decision, eligibility determination, or verified outcome."] },
  { heading: "Required human review", items: ["A qualified person must review material before consequential use.", "Sources, dates, calculations, rights, and required disclosures must be checked.", "Only an authorized person may send, submit, publish, approve, pay, sign, or change an official record.", "Protected characteristics and sensitive data must not be used improperly in decisions.", "Automated actions must stay within the authority, scope, and controls defined for the deployment."] },
  { heading: "Known limitations", items: ["AI can produce inaccurate, incomplete, outdated, biased, or non-original output.", "A citation or confident tone does not prove that a claim is true.", "Connected information may be incomplete or governed by a different system of record.", "Performance in a demonstration, synthetic environment, or pilot does not establish production outcomes."] },
  { heading: "Customer configuration", paragraphs: ["Providers, data sources, logging, retention, approval gates, and available controls vary by product and engagement. Material deployment-specific terms belong in the order, statement of work, security exhibit, or data-processing addendum. Questions: info@perpetualcore.com."] },
] };

export const securityPractices: LegalDocument = { title: "Security & Data Practices", description: "A plain-language description of Perpetual Core's security approach and the evidence buyers should request for a specific deployment.", effective, notice: "This page is not a certification, audit report, service-level agreement, or representation that every product has identical controls.", sections: [
  { heading: "Security principles", items: ["Collect and retain only information needed for a defined purpose.", "Use individual authentication, least privilege, and separated customer or entity boundaries.", "Encrypt supported traffic in transit and use provider-supported encryption at rest.", "Keep consequential actions reviewable and attributable.", "Use controlled secrets and avoid embedding credentials in source code.", "Maintain incident, vulnerability, backup, and recovery procedures proportionate to the service."] },
  { heading: "Customer diligence", paragraphs: ["Before production use, buyers should request the deployment-specific architecture, subprocessors, data flows, retention, access model, recovery objectives, incident terms, test evidence, and any required regulatory agreement. Public marketing language does not replace that review."] },
  { heading: "Regulated environments", paragraphs: ["Healthcare, education, government, financial, and other regulated deployments require an expressly scoped environment and written terms. Do not infer HIPAA, FERPA, PCI DSS, SOC 2, FedRAMP, or other compliance from general security practices. Perpetual Core will state a certification or regulated authorization only when current evidence supports it."] },
  { heading: "Report a vulnerability", paragraphs: ["Send a concise description and reproduction steps to info@perpetualcore.com with the subject line ‘Security report.’ Do not access, alter, retain, or disclose data that is not yours; do not disrupt service; and allow a reasonable period for investigation before public disclosure."] },
] };

export const accessibilityStatement: LegalDocument = { title: "Accessibility Statement", description: "Perpetual Core's commitment to accessible digital experiences and a direct path for reporting barriers.", effective, sections: [
  { heading: "Our commitment", paragraphs: ["Perpetual Core aims to make its public digital experiences usable by people with disabilities and targets WCAG 2.2 Level AA where reasonably applicable. Accessibility is an ongoing product and content practice, not a one-time certification."] },
  { heading: "What we work toward", items: ["Keyboard-operable navigation and controls.", "Visible focus and understandable headings and labels.", "Sufficient text and interface contrast.", "Text alternatives for meaningful images and names for icon controls.", "Reduced-motion support and responsive layouts.", "Accessible error, status, and form instructions."] },
  { heading: "Need an accommodation or found a barrier?", paragraphs: ["Email info@perpetualcore.com with the subject line ‘Accessibility,’ the page or feature, the barrier you encountered, and your preferred contact method. We will acknowledge the report and work toward an accessible alternative or correction."] },
  { heading: "Third-party content", paragraphs: ["Some linked or embedded third-party services are outside our direct control. We still want to know when they block access so we can provide an alternative where reasonably possible."] },
] };

export const cookiePolicy: LegalDocument = { title: "Cookie Notice", description: "How Perpetual Core uses browser storage and similar technologies.", effective, sections: [
  { heading: "What we use", paragraphs: ["Perpetual Core may use cookies, local storage, and similar technologies needed for authentication, security, preferences, service operation, and measurement. The exact technologies vary by product and may change as vendors or configurations change."] },
  { heading: "Categories", items: ["Strictly necessary: authentication, session continuity, security, load balancing, and requested functionality.", "Preference: saved interface or consent choices.", "Measurement: aggregated or pseudonymous product and performance analytics where enabled.", "Payment and embedded services: technologies set by a payment processor or an expressly loaded third-party feature."] },
  { heading: "Your choices", paragraphs: ["You can use browser settings and any available consent controls to limit nonessential technologies. Blocking necessary storage may prevent login, checkout, or other requested features. Where applicable law requires recognition of supported opt-out signals, we will process them accordingly."] },
  { heading: "Contact", paragraphs: ["info@perpetualcore.com"] },
] };

export const legalDocuments = { privacy: privacyPolicy, terms: termsOfService, cookies: cookiePolicy, "acceptable-use": acceptableUsePolicy, ai: aiDisclosure, security: securityPractices, accessibility: accessibilityStatement } as const;
