import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { SiteNav } from "@/components/next-site/SiteNav";
import { SiteFooter } from "@/components/next-site/SiteFooter";

export const metadata={title:"Field Notes — Perpetual Core",description:"Operator notes on what production AI costs, what makes an install durable, and how to evaluate outcomes."};
const notes=[
  {n:"001",slug:"the-75k-floor",tag:"ECONOMICS",title:"WHAT AN AI OPERATING SYSTEM ACTUALLY TAKES.",body:"The operating map, data surface, workflow ownership, adoption, governance, and expansion path behind a durable install.",date:"MAY 22, 2026",read:"5 MIN",color:"#d7ff3f"},
  {n:"002",slug:"what-an-ai-install-actually-costs",tag:"BUYER GUIDE",title:"WHAT AN AI INSTALL ACTUALLY COSTS.",body:"Four cost buckets most proposals blur: subscriptions, engineering, integration debt, and outcome evaluation.",date:"MAY 20, 2026",read:"6 MIN",color:"#ff6338"},
  {n:"003",slug:"outcome-eval-the-line-item-every-ai-install-skips",tag:"EVIDENCE",title:"THE LINE ITEM EVERY AI INSTALL SKIPS.",body:"Without outcome evaluation, you do not have an install. You have a demo that ran once.",date:"MAY 20, 2026",read:"5 MIN",color:"#2457ff"},
];
export default function BlogPage(){return <div className="min-h-screen bg-[#12151c] text-white"><SiteNav/><main id="main-content" className="pt-28">
  <section className="px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-[1500px]"><div className="flex items-center justify-between"><p className="text-[10px] font-black tracking-[.16em] text-[#d7ff3f]">FIELD NOTES / THE INSTALL</p><p className="hidden text-[10px] font-black tracking-[.14em] text-white/35 sm:block">WRITTEN FROM THE OPERATING FLOOR</p></div><h1 className="mt-8 max-w-7xl text-[clamp(4rem,9vw,8.5rem)] font-black leading-[.79] tracking-[-.08em]">IDEAS ARE<br/>CHEAP.<br/><span className="text-white/25">INSTALLS ARE NOT.</span></h1><div className="mt-12 grid gap-6 border-t border-white/10 pt-8 lg:grid-cols-2"><p className="text-2xl font-black leading-9">Notes for buyers and operators who need AI to survive contact with real work.</p><p className="max-w-2xl text-lg leading-8 text-white/50">No invented outcomes. No autonomous-company mythology. Just economics, governance, operating design, and what we learn while building.</p></div></div></section>
  <section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-[1500px] divide-y divide-white/10 border-y border-white/10">{notes.map(note=><Link href={`/blog/${note.slug}`} key={note.n} className="group grid gap-7 py-10 transition-colors hover:bg-white/[.025] md:grid-cols-[80px_1.15fr_.85fr_60px] md:items-center md:px-5"><span className="text-xs font-black text-white/25">{note.n}</span><div><span className="text-[9px] font-black tracking-[.14em]" style={{color:note.color}}>{note.tag}</span><h2 className="mt-4 max-w-3xl text-3xl font-black leading-[.95] tracking-[-.05em] sm:text-5xl">{note.title}</h2><p className="mt-4 text-[10px] font-black tracking-[.13em] text-white/30">{note.date} / {note.read}</p></div><p className="max-w-xl text-base leading-7 text-white/50">{note.body}</p><span className="grid h-12 w-12 place-items-center rounded-full border border-white/15 transition-colors group-hover:bg-white group-hover:text-black"><ArrowUpRight className="h-5 w-5"/></span></Link>)}</div></section>
  <section className="bg-[#d7ff3f] px-5 py-16 text-[#12151c] sm:px-8 sm:py-20"><div className="mx-auto flex max-w-[1500px] flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black tracking-[.16em]">FROM READING TO OPERATING</p><h2 className="mt-5 max-w-5xl text-4xl font-black leading-[.92] tracking-[-.055em] sm:text-6xl">BUY THE SMALLEST SYSTEM THAT CAN PROVE THE NEXT DECISION.</h2></div><Link href="/packages" className="inline-flex min-h-14 shrink-0 items-center justify-center rounded-2xl bg-[#12151c] px-6 font-black text-white">See ways to start <ArrowRight className="ml-3 h-5 w-5"/></Link></div></section>
  </main><SiteFooter/></div>}
