"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { FileText, FileSpreadsheet, Presentation, Download } from "lucide-react";

export default function TestDocumentsPage() {
  const [loading, setLoading] = useState<string | null>(null);

  const generateDocument = async (type: "powerpoint" | "pdf" | "excel") => {
    setLoading(type);

    try {
      let payload: any = {
        type,
        title: `Test ${type === "powerpoint" ? "Presentation" : type === "pdf" ? "Document" : "Spreadsheet"}`,
      };

      if (type === "powerpoint") {
        payload.slides = [
          {
            title: "Introduction",
            content: [
              "Welcome to the AI-powered presentation",
              "Created automatically by our system",
              "Professional and beautiful slides",
            ],
          },
          {
            title: "Key Features",
            content: [
              "Instant generation",
              "Professional design",
              "Easy customization",
              "Free and open source",
            ],
          },
          {
            title: "Use Cases",
            content: [
              "Business presentations",
              "Educational content",
              "Project proposals",
              "Team meetings",
            ],
          },
        ];
      } else if (type === "pdf") {
        payload.content = `This is a test PDF document generated by the AI system.

It demonstrates the ability to create professional PDF documents on demand.

Key Features:
- Instant generation
- Professional formatting
- Downloadable files
- Free and easy to use

This technology can be used for:
1. Reports and documentation
2. Invoices and receipts
3. Certificates and diplomas
4. Contracts and agreements

The system uses jsPDF library to create high-quality PDF documents that can be customized with various fonts, colors, and layouts.`;
      } else if (type === "excel") {
        payload.data = [
          { Name: "John Doe", Age: 30, Department: "Engineering", Salary: 75000 },
          { Name: "Jane Smith", Age: 28, Department: "Marketing", Salary: 65000 },
          { Name: "Bob Johnson", Age: 35, Department: "Sales", Salary: 70000 },
          { Name: "Alice Williams", Age: 32, Department: "HR", Salary: 60000 },
          { Name: "Charlie Brown", Age: 29, Department: "Engineering", Salary: 80000 },
        ];
      }

      const response = await fetch("/api/generate-document", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || "Failed to generate document");
      }

      // Download the file
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `test-${type}.${type === "powerpoint" ? "pptx" : type === "pdf" ? "pdf" : "xlsx"}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

      alert(`${type.toUpperCase()} generated successfully!`);
    } catch (error: any) {
      console.error("Error generating document:", error);
      alert(`Error: ${error.message}`);
    } finally {
      setLoading(null);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-2 text-center">
          Document Generation Test
        </h1>
        <p className="text-gray-600 text-center mb-8">
          Test PowerPoint, PDF, and Excel document generation
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* PowerPoint Card */}
          <Card className="p-6 hover:shadow-lg transition-shadow">
            <div className="flex flex-col items-center text-center">
              <div className="bg-orange-100 p-4 rounded-full mb-4">
                <Presentation className="h-8 w-8 text-orange-600" />
              </div>
              <h2 className="text-xl font-semibold mb-2">PowerPoint</h2>
              <p className="text-sm text-gray-600 mb-4">
                Generate a professional presentation with multiple slides
              </p>
              <Button
                onClick={() => generateDocument("powerpoint")}
                disabled={loading === "powerpoint"}
                className="w-full bg-orange-600 hover:bg-orange-700"
              >
                {loading === "powerpoint" ? (
                  "Generating..."
                ) : (
                  <>
                    <Download className="h-4 w-4 mr-2" />
                    Generate .pptx
                  </>
                )}
              </Button>
            </div>
          </Card>

          {/* PDF Card */}
          <Card className="p-6 hover:shadow-lg transition-shadow">
            <div className="flex flex-col items-center text-center">
              <div className="bg-red-100 p-4 rounded-full mb-4">
                <FileText className="h-8 w-8 text-red-600" />
              </div>
              <h2 className="text-xl font-semibold mb-2">PDF</h2>
              <p className="text-sm text-gray-600 mb-4">
                Create a formatted PDF document with text content
              </p>
              <Button
                onClick={() => generateDocument("pdf")}
                disabled={loading === "pdf"}
                className="w-full bg-red-600 hover:bg-red-700"
              >
                {loading === "pdf" ? (
                  "Generating..."
                ) : (
                  <>
                    <Download className="h-4 w-4 mr-2" />
                    Generate .pdf
                  </>
                )}
              </Button>
            </div>
          </Card>

          {/* Excel Card */}
          <Card className="p-6 hover:shadow-lg transition-shadow">
            <div className="flex flex-col items-center text-center">
              <div className="bg-green-100 p-4 rounded-full mb-4">
                <FileSpreadsheet className="h-8 w-8 text-green-600" />
              </div>
              <h2 className="text-xl font-semibold mb-2">Excel</h2>
              <p className="text-sm text-gray-600 mb-4">
                Build a spreadsheet with data tables and formatting
              </p>
              <Button
                onClick={() => generateDocument("excel")}
                disabled={loading === "excel"}
                className="w-full bg-green-600 hover:bg-green-700"
              >
                {loading === "excel" ? (
                  "Generating..."
                ) : (
                  <>
                    <Download className="h-4 w-4 mr-2" />
                    Generate .xlsx
                  </>
                )}
              </Button>
            </div>
          </Card>
        </div>

        <Card className="mt-8 p-6 bg-blue-50 border-blue-200">
          <h3 className="font-semibold text-lg mb-2">How it works:</h3>
          <ul className="text-sm text-gray-700 space-y-1">
            <li>1. Click any button above to generate a test document</li>
            <li>2. The document will be created on the server</li>
            <li>3. Your browser will automatically download the file</li>
            <li>4. Open the file to verify it works correctly</li>
          </ul>
        </Card>
      </div>
    </div>
  );
}
