import { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Privacy Policy | Perpetual Core RFP & Proposal Engine",
  description:
    "Privacy Policy for the Perpetual Core RFP & Proposal Engine — how we collect, use, and protect your organization data and vault documents.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white dark:from-gray-900 dark:to-gray-800">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="mb-8">
          <Button variant="ghost" asChild className="mb-4">
            <Link href="/">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Home
            </Link>
          </Button>
          <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
          <p className="text-muted-foreground">Last updated: June 1, 2026</p>
        </div>

        {/* Draft banner */}
        <div className="mb-8 rounded-lg border border-amber-400 bg-amber-50 dark:bg-amber-950/30 dark:border-amber-500 px-5 py-4">
          <p className="text-sm font-semibold text-amber-800 dark:text-amber-300">
            Draft — pending counsel review.
          </p>
          <p className="text-sm text-amber-700 dark:text-amber-400 mt-1">
            This content is provided for informational purposes only and does
            not constitute legal advice. Review with qualified counsel before
            relying on it.
          </p>
        </div>

        <div className="prose prose-gray dark:prose-invert max-w-none">
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
            <p>
              Perpetual Core LLC (&quot;we,&quot; &quot;our,&quot; or
              &quot;us&quot;) operates the RFP &amp; Proposal Engine at{" "}
              <strong>rfp.perpetualcore.com</strong>. This Privacy Policy
              explains how we collect, use, and protect information when you use
              the Service. By using the Service, you consent to the practices
              described here.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">
              2. Information We Collect
            </h2>

            <h3 className="text-xl font-semibold mb-2">
              2.1 Account &amp; Organization Data
            </h3>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>
                <strong>Account Information:</strong> Email address, name,
                password (hashed), organization name, and role within your
                organization.
              </li>
              <li>
                <strong>Organization Profile:</strong> Mission statement,
                program areas, geographic focus, NTEE / NAICS codes, past
                funding history, and other details you provide to improve
                opportunity matching.
              </li>
              <li>
                <strong>Billing Information:</strong> Subscription tier and
                payment status (payment card details are processed by Stripe and
                are not stored by us).
              </li>
            </ul>

            <h3 className="text-xl font-semibold mb-2 mt-4">
              2.2 Vault Documents
            </h3>
            <p>
              You may upload documents to your organization&apos;s vault (PDF,
              DOCX, and similar formats), such as past proposals, annual reports,
              program descriptions, and budgets. These documents are stored
              securely and processed by AI providers to generate embeddings and
              proposal drafts. See Section 4 (Sub-processors) for details.
            </p>

            <h3 className="text-xl font-semibold mb-2 mt-4">
              2.3 Proposal Content
            </h3>
            <p>
              Proposal drafts, fit scores, compliance assessments, and related
              content generated by the Service are stored in association with
              your account.
            </p>

            <h3 className="text-xl font-semibold mb-2 mt-4">
              2.4 Usage Data
            </h3>
            <p>
              We automatically collect usage data including features accessed,
              actions taken, timestamps, IP addresses, browser type, and error
              logs for the purpose of operating and improving the Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">
              3. How We Use Your Information
            </h2>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>
                <strong>Opportunity Matching:</strong> Compare your organization
                profile and vault documents against public funding opportunities
                to generate fit scores and ranked results.
              </li>
              <li>
                <strong>Proposal Drafting:</strong> Send vault document content
                and opportunity details to AI providers (Anthropic Claude,
                OpenAI) to generate proposal drafts, section summaries, and
                compliance notes.
              </li>
              <li>
                <strong>Embeddings:</strong> Convert vault documents and
                opportunity text into vector embeddings for semantic search and
                retrieval-augmented generation.
              </li>
              <li>
                <strong>Account &amp; Billing Management:</strong> Create and
                maintain your account, process payments, and manage
                subscriptions.
              </li>
              <li>
                <strong>Service Operations:</strong> Diagnose issues, improve
                accuracy, develop new features, and maintain security.
              </li>
              <li>
                <strong>Legal Compliance:</strong> Comply with applicable law
                and enforce our Terms of Service.
              </li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">
              4. Third-Party Sources &amp; Sub-processors
            </h2>

            <h3 className="text-xl font-semibold mb-2">
              4.1 Government &amp; Public Data Sources
            </h3>
            <p>
              Opportunity data is pulled from publicly available government
              databases:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>SAM.gov (federal contracts and grants)</li>
              <li>Grants.gov (federal grant solicitations)</li>
              <li>SBIR.gov (small business innovation research)</li>
              <li>NIH (National Institutes of Health awards and notices)</li>
              <li>NSF (National Science Foundation award data)</li>
              <li>NYC and New Jersey municipal open-data portals</li>
            </ul>
            <p className="mt-2">
              These sources&apos; own terms govern their data. We do not
              redistribute license-restricted data in ways that violate those
              terms.
            </p>

            <h3 className="text-xl font-semibold mb-2 mt-4">
              4.2 AI Providers
            </h3>
            <p>
              Vault document content and opportunity context are sent to the
              following AI providers to generate embeddings and proposal content:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>
                <strong>Anthropic (Claude):</strong> Subject to Anthropic&apos;s
                privacy policy and commercial API terms.
              </li>
              <li>
                <strong>OpenAI:</strong> Subject to OpenAI&apos;s privacy policy
                and API terms.
              </li>
            </ul>
            <p className="mt-2">
              For details on how AI processes your data and applicable
              federal-contractor AI-use disclosures, see our{" "}
              <Link
                href="/ai-disclosure"
                className="text-primary hover:underline"
              >
                AI-Use Disclosure
              </Link>
              .
            </p>

            <h3 className="text-xl font-semibold mb-2 mt-4">
              4.3 Infrastructure Sub-processors
            </h3>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>
                <strong>Supabase:</strong> Database storage, authentication, and
                row-level security (RLS) tenant isolation.
              </li>
              <li>
                <strong>Stripe:</strong> Payment processing and subscription
                management.
              </li>
              <li>
                <strong>Vercel:</strong> Application hosting and edge delivery.
              </li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">5. Data Security</h2>
            <p>
              We implement industry-standard security measures to protect your
              information:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>
                <strong>Encryption:</strong> Data encrypted in transit (TLS) and
                at rest.
              </li>
              <li>
                <strong>Tenant Isolation:</strong> Row-level security (RLS)
                policies in Supabase ensure each organization can only access
                its own vault documents, proposals, and profile data.
              </li>
              <li>
                <strong>Access Controls:</strong> Role-based access controls and
                principle of least privilege.
              </li>
              <li>
                <strong>Authentication:</strong> Secure password hashing;
                session tokens scoped to your organization.
              </li>
            </ul>
            <p className="mt-4">
              No method of transmission or storage is 100% secure. While we
              strive to protect your information, we cannot guarantee absolute
              security.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">6. Data Retention</h2>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>
                <strong>Account Data:</strong> Retained while your account is
                active. Deleted within 30 days of account closure upon request.
              </li>
              <li>
                <strong>Vault Documents:</strong> Retained until you delete them
                or close your account.
              </li>
              <li>
                <strong>Proposal Drafts &amp; Scores:</strong> Retained while
                your account is active; deletable via the Service.
              </li>
              <li>
                <strong>Usage Logs:</strong> Retained up to 90 days for security
                and operational purposes.
              </li>
              <li>
                <strong>Billing Records:</strong> Retained for 7 years for tax
                and legal compliance.
              </li>
            </ul>
            <p className="mt-4">
              AI provider processing of your content for embedding and draft
              generation is covered by each provider&apos;s data retention
              policies. Under standard enterprise API terms, providers do not
              retain input data to train their models.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">7. Your Rights</h2>
            <p>
              You may request access to, correction of, or deletion of your
              personal data at any time by contacting us. You may also export
              your vault documents through the Service. California residents and
              EEA users have additional rights under applicable law (CCPA /
              GDPR). Contact us to exercise any of these rights.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">8. Contact</h2>
            <p>
              Questions, requests, or concerns about this Privacy Policy may be
              directed to:
            </p>
            <div className="mt-2 space-y-1">
              <p>
                <strong>Email:</strong> privacy@perpetualcore.com
              </p>
              <p>
                <strong>Operator:</strong> Perpetual Core LLC
              </p>
            </div>
          </section>
        </div>

        <div className="mt-12 p-6 bg-muted rounded-lg">
          <p className="text-sm text-muted-foreground">
            This Privacy Policy describes how Perpetual Core LLC collects, uses,
            and protects information in connection with the RFP &amp; Proposal
            Engine. For questions or to exercise your privacy rights, contact us
            at privacy@perpetualcore.com.
          </p>
        </div>
      </div>
    </div>
  );
}
