import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Download, ShieldCheck } from "lucide-react";
import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import { SkipLink } from "@/components/ui/accessibility";
export const metadata: Metadata = { title: "Legal & Trust Center", description: "Public policies, AI boundaries, security practices, accessibility commitments, and customer contracting documents for Perpetual Core." };
const policies = [["Privacy Policy", "/privacy", "Data collection, use, disclosure, retention, and choices."], ["Terms of Service", "/terms", "Baseline terms when no signed customer agreement controls."], ["Cookie Notice", "/cookies", "Browser storage, service operation, and measurement choices."], ["Acceptable Use", "/legal/acceptable-use", "Prohibited use and consequential-decision safeguards."], ["AI Use & Human Authority", "/legal/ai", "What AI can prepare and what only an authorized human can decide."], ["Security & Data Practices", "/legal/security", "Security principles, diligence, and regulated-data boundaries."], ["Accessibility Statement", "/legal/accessibility", "Our WCAG 2.2 AA target and barrier-reporting path."]] as const;
const contracts = [["Master Services Agreement", "/legal/contracts/perpetual-core-master-services-agreement.pdf"], ["Statement of Work Template", "/legal/contracts/perpetual-core-statement-of-work-template.pdf"], ["Mutual NDA", "/legal/contracts/perpetual-core-mutual-nda.pdf"], ["Data Processing Addendum", "/legal/contracts/perpetual-core-data-processing-addendum.pdf"], ["Business Associate Addendum", "/legal/contracts/perpetual-core-business-associate-addendum.pdf"]] as const;
export default function LegalCenterPage() { return <div className="min-h-screen bg-[#f7f6f2] text-[#17171b]"><SkipLink /><Navbar /><main id="main-content"><section className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 sm:py-24"><div className="max-w-4xl"><div className="flex items-center gap-3 font-mono text-[11px] uppercase tracking-[0.18em] text-[#5146c7]"><ShieldCheck className="h-4 w-4" aria-hidden="true" /> Legal / trust / authority</div><h1 className="mt-7 text-5xl font-semibold leading-[0.98] tracking-[-0.05em] sm:text-7xl">Clear rules for serious operating work.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[#5a5a63]">These documents define the public baseline. A signed customer agreement, order, statement of work, data-processing addendum, or Business Associate Agreement controls for a specific engagement.</p><div className="mt-7 border-l-4 border-[#5146c7] bg-white p-5 text-sm leading-6"><strong>Important:</strong> Templates are negotiation-ready starting points, not a substitute for legal advice. Regulated or high-value engagements require counsel review and deployment-specific exhibits.</div></div></section><section className="border-t border-black/10"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[240px_1fr]"><h2 className="text-xs font-semibold uppercase tracking-[0.18em]">Public policies</h2><div className="grid gap-px overflow-hidden border border-black/10 bg-black/10 sm:grid-cols-2">{policies.map(([name, href, body]) => <Link key={href} href={href} className="group min-h-44 bg-white p-6 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#5146c7]"><h3 className="text-xl font-semibold">{name}</h3><p className="mt-3 text-sm leading-6 text-[#5c5c65]">{body}</p><span className="mt-6 inline-flex items-center text-sm font-medium text-[#5146c7]">Read document <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" aria-hidden="true" /></span></Link>)}</div></div></section><section className="border-t border-black/10 bg-[#111116] text-white"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[240px_1fr]"><div><h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-white/70">Customer contracts</h2><p className="mt-4 text-sm leading-6 text-white/60">Downloadable starting forms. Final documents require the parties, scope, commercial terms, and signatures.</p></div><div className="divide-y divide-white/10 border-y border-white/10">{contracts.map(([name, href]) => <a key={href} href={href} className="group flex min-h-20 items-center justify-between gap-5 py-5 text-lg font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#54e6b1]"><span>{name}</span><span className="inline-flex items-center text-sm text-[#54e6b1]">PDF <Download className="ml-2 h-4 w-4" aria-hidden="true" /></span></a>)}</div></div></section></main><Footer /></div>; }
