import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { SiteNav } from "@/components/next-site/SiteNav";
import { SiteFooter } from "@/components/next-site/SiteFooter";

const companies = [
  { n: "01", name: "KEPT COUNT", state: "PUBLIC FLAGSHIP", color: "#ff6338", href: "https://keptcount.com", copy: "AI care operations for organizations coordinating Medicare and community-health work.", detail: "Explore the product, operating model, and current evidence boundaries.", action: "Visit Kept Count" },
  { n: "02", name: "WORKFORCE", state: "DESIGN-PARTNER SYSTEM", color: "#d7ff3f", href: "/contact-sales?intent=workforce", copy: "One governed operating layer for enrollment, learning, case management, placement, and reporting.", detail: "Available for design-partner conversations; not presented as a general self-serve product.", action: "Discuss Workforce" },
  { n: "03", name: "THE NEXT COMPANY", state: "EARNED, NOT ANNOUNCED", color: "#2457ff", href: "/studio", copy: "A repeated operating problem becomes a company only after the Studio proves the market, workflow, and buyer.", detail: "See how scoped implementation can become durable market infrastructure.", action: "See the build path" },
];

export const metadata = { title: "Companies — Perpetual Core", description: "Focused companies built on the Perpetual Core operating layer." };

export default function CompaniesPage() {
  return <div className="min-h-screen bg-[#12151c] text-white"><SiteNav /><main id="main-content" className="pt-28">
    <section className="px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-[1500px]"><p className="text-[10px] font-black tracking-[.16em] text-[#d7ff3f]">FOCUSED COMPANIES / DISTINCT MARKETS</p><div className="mt-7 grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><h1 className="max-w-5xl text-[clamp(3.6rem,7vw,7rem)] font-black leading-[.82] tracking-[-.075em]">WHEN A MARKET NEEDS MORE THAN A TOOL.</h1><div className="border-l-2 border-[#ff6338] pl-6 sm:pl-8"><p className="text-2xl font-bold leading-9">Perpetual Core builds shared systems. A focused company goes deeper into one market, buyer, and operating result.</p><p className="mt-4 text-base leading-7 text-white/60">This page shows what is public, what is available for design partnership, and what has not yet earned a launch.</p></div></div></div></section>
    <section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-[1500px] divide-y divide-white/10 border-y border-white/10">{companies.map(c => <Link key={c.n} href={c.href} className="group grid cursor-pointer gap-8 py-10 transition-colors hover:bg-white/[.03] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#d7ff3f]/30 md:grid-cols-[90px_1.1fr_.9fr_150px] md:items-center md:px-5"><span className="text-sm font-black text-white/25">{c.n}</span><div><span className="inline-block rounded-full px-3 py-2 text-[9px] font-black tracking-[.14em] text-black" style={{backgroundColor:c.color}}>{c.state}</span><h2 className="mt-5 text-4xl font-black tracking-[-.05em] sm:text-6xl">{c.name}</h2></div><div><p className="text-lg font-bold leading-7">{c.copy}</p><p className="mt-3 text-sm leading-6 text-white/50">{c.detail}</p></div><span className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 px-4 text-sm font-black transition-colors group-hover:bg-white group-hover:text-black">{c.action}<ArrowUpRight aria-hidden="true" className="ml-2 h-4 w-4" /></span></Link>)}</div></section>
    <section className="bg-[#ff6338] px-5 py-20 text-[#12151c] sm:px-8"><div className="mx-auto flex max-w-[1500px] flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><h2 className="max-w-4xl text-4xl font-black leading-[.9] tracking-[-.06em] sm:text-6xl">WE DO NOT LAUNCH COMPANIES TO FILL A GRID.</h2><Link href="/studio" className="inline-flex min-h-14 shrink-0 items-center justify-center rounded-2xl bg-[#12151c] px-6 font-black text-white">See how a build earns scale</Link></div></section>
  </main><SiteFooter /></div>;
}
