"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import {
  ArrowRight,
  Search,
  Mic,
  Database,
  PenLine,
  Sparkles,
  ShieldCheck,
  CheckCircle2,
  XCircle,
  Lock,
  Clock,
  Upload,
  Building2,
  Plug,
  Radar,
} from "lucide-react";

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <div className="mb-6 flex items-center gap-3 font-mono text-[11px] uppercase tracking-[0.22em] text-zinc-500">
      <span className="h-px w-8 bg-zinc-700" />
      {children}
    </div>
  );
}

const fadeUp = {
  hidden: { opacity: 0, y: 16 },
  visible: { opacity: 1, y: 0 },
};

const stages = [
  {
    num: "01",
    name: "Discovery",
    icon: Search,
    agent:
      "Discovery agent scans SAM.gov, Grants.gov, Simpler Grants, NY State Grants Gateway, NYC DYCD, Candid, and SBIR.gov on a 6-hour cron. Each opportunity gets a fit score (NAICS overlap, keyword alignment, geo, dollar band, prior funder history). Anything ≥ 80 fit becomes a brief.",
    you: "Open the morning brief. Three to five opportunities, ranked. Click into the one that fits, dismiss the rest.",
    time: "Runs 24/7. ~3 min of your time per morning.",
  },
  {
    num: "02",
    name: "Vault",
    icon: Database,
    agent:
      "Vault agent retrieves the artifacts that ground this proposal — past wins with the same funder, capacity statements that match the program, partner letters, logic models, 990s. Top-k chunks via pgvector cosine similarity, scoped to your tenant.",
    you: "Confirm the retrieval is on-target. Add anything missing. The vault is yours — uploads stay in your tenant, embeddings are namespaced.",
    time: "30 seconds to scan. Most users skip — it's right.",
  },
  {
    num: "03",
    name: "Draft",
    icon: PenLine,
    agent:
      "Drafting agent writes section by section in your voice fingerprint. Sonnet 4 by default; Opus 4.7 for evaluation-critical sections. Every claim is grounded in a vault artifact. Anything we can't cite gets a [VERIFY] flag — not silently invented.",
    you: "Read the draft. Adjust voice if it drifted. Resolve [VERIFY] flags by either pointing to a vault doc or rewriting the claim.",
    time: "10–25 minutes per section, vs. 2–4 hours from scratch.",
  },
  {
    num: "04",
    name: "Reviewer",
    icon: Sparkles,
    agent:
      "Reviewer sub-agent (Opus 4.7) reads your draft against the funder's evaluation rubric. It scores 0–100 and emits specific revision requests with the rubric language cited. Brutal, not polite.",
    you: "Accept the revisions you agree with. Push back on the ones that don't fit your strategy. The reviewer doesn't get a vote on the final draft — you do.",
    time: "5–10 minutes per revision pass. Usually 1–2 passes.",
  },
  {
    num: "05",
    name: "Compliance",
    icon: ShieldCheck,
    agent:
      "Compliance agent runs deterministic checks: page count per section, font size, line spacing, margins, required attachments (W-9, audit, letters, SF-424 family), budget arithmetic, indirect rate caps, eligibility, due-date timezone, 24-hour buffer.",
    you: "Read the pass/fail report. Fix what's red. Re-run until clean.",
    time: "Under a minute to run. Fixes vary.",
  },
  {
    num: "06",
    name: "Submit",
    icon: CheckCircle2,
    agent:
      "Engine assembles the final PDF/docx package with the funder's required structure, exports a clean submission bundle, and writes the full agent activity log to your audit trail.",
    you: "You submit. Always. The platform never auto-submits, never signs anything, never wires money. The last click is human.",
    time: "Whenever you're ready. The clock stops at submit-ready.",
  },
];

const scenario = [
  {
    stamp: "TUE 09:14",
    label: "Discovery",
    body: "DYCD posts a $650K Workforce Learning Grant for community-based orgs serving 18–24 in NYC. Scraper picks it up at the next 6-hour tick.",
  },
  {
    stamp: "TUE 09:22",
    label: "Match",
    body: "Fit score: 94. NAICS aligns (624310). Geo aligns. Dollar band aligns. Prior win with NYC HRA carries the funder-history weight. Brief generated by Sonnet 4.",
  },
  {
    stamp: "TUE 09:28",
    label: "Notify",
    body: "Slack ping in #capture: 'New 94-fit. DYCD-WLG-2026. $650K. Due 5/29 17:00 ET.' Linked straight to the proposal workspace.",
  },
  {
    stamp: "TUE 10:03",
    label: "Open file",
    body: "ED clicks in. Workspace pre-loaded: solicitation excerpt parsed, evaluation rubric extracted, retrieved vault artifacts (last DYCD Workforce win, current capacity statement, two partner letters from 2024).",
  },
  {
    stamp: "TUE 11:40",
    label: "First drafts",
    body: "Drafting agent returns Need, Approach, Org Capacity, Logic Model in voice. Six [VERIFY] flags on enrollment numbers and outcome stats. Three resolved from vault, three flagged for staff to confirm.",
  },
  {
    stamp: "WED 10:15",
    label: "Reviewer pass",
    body: "Opus 4.7 scores 78/100. Flags weak theory of change linkage on Approach → Outcomes; missing evaluation timeline; Logic Model needs a quantified short-term indicator.",
  },
  {
    stamp: "WED 14:30",
    label: "Revisions",
    body: "Writer accepts 7 of 9 revision requests. Pushes back on two that contradicted org strategy. Reviewer rescores 91/100.",
  },
  {
    stamp: "THU 11:00",
    label: "Compliance",
    body: "Page count clean. Font 11pt Calibri (DYCD allows 11+). Budget sums. Indirect at 10% — under the 12% cap. Three required attachments missing: pulled from vault, dropped in.",
  },
  {
    stamp: "THU 16:20",
    label: "Submit-ready",
    body: "Final PDF assembled. Audit log exported. ED reviews end-to-end one more time, signs cover letter, submits via DYCD portal.",
  },
  {
    stamp: "FRI 09:00",
    label: "Filed",
    body: "Confirmation receipt logged against the proposal record. Eight days early. Total staff time: ~6 hours instead of the usual 40+.",
  },
];

const agents = [
  {
    icon: Search,
    name: "Discovery agent",
    role: "Always-on opportunity scanner across federal, state, city, and foundation sources.",
    touches: "SAM.gov, Grants.gov, Simpler Grants, NY State Grants Gateway, NYC DYCD/HRA/DOE, Candid, SBIR.gov.",
    doesnt: "Submit on your behalf. Pay subscription fees on your behalf. Reach out to program officers.",
  },
  {
    icon: Mic,
    name: "Voice agent",
    role: "Builds and refreshes your voice fingerprint from past wins, annual reports, and founder letters.",
    touches: "Documents you upload to your vault. JSON fingerprint stored on your org row.",
    doesnt: "Train any model outside your tenant. Share your voice with other customers. Write copy without grounding.",
  },
  {
    icon: Database,
    name: "Vault agent",
    role: "Retrieves the right artifacts from your tenant for grounding every section.",
    touches: "Your vault: past proposals, partner letters, logic models, 990s, capacity statements, leadership bios.",
    doesnt: "Read other tenants' vaults. Persist content outside your encrypted storage.",
  },
  {
    icon: PenLine,
    name: "Drafting agent",
    role: "Generates section-level drafts in your voice, grounded in your vault.",
    touches: "Section drafts, citations, [VERIFY] markers. Sonnet 4 default, Opus 4.7 for evaluation-critical.",
    doesnt: "Invent partners, fabricate outcomes, cite sources outside your vault, ship un-flagged unverified claims.",
  },
  {
    icon: Sparkles,
    name: "Reviewer agent",
    role: "Scores drafts against the funder's evaluation rubric and requests specific revisions.",
    touches: "Solicitation excerpts, extracted rubrics, your draft. Opus 4.7 — the high-stakes critic.",
    doesnt: "Override your judgment. Edit your draft directly without your approval.",
  },
  {
    icon: ShieldCheck,
    name: "Compliance agent",
    role: "Deterministic pre-submit gate for page rules, budgets, attachments, eligibility, and timing.",
    touches: "Final assembled package, solicitation requirements, SF-424 family, cost share math.",
    doesnt: "Submit. Sign anything. Make legal or eligibility judgments — it flags, you decide.",
  },
];

const humanOnly = [
  { label: "Final submission", body: "The last click is always yours. We assemble the bundle. You file it." },
  { label: "Signing", body: "No autopen, no signature stamp, no e-sign on your behalf. Cover letters, certifications, SF-LLL — your hand." },
  { label: "Budget approval", body: "We do the math. You approve the numbers. Your CFO and your board are the source of truth." },
  { label: "Partner outreach", body: "We surface which partners you've used before. We don't email them. Relationships are yours to maintain." },
  { label: "Eligibility calls", body: "We flag eligibility risks. We never say 'you qualify' on your behalf to a federal officer." },
  { label: "Anything irreversible", body: "If undoing it requires a phone call, a lawyer, or an apology — the platform doesn't do it. You do." },
];

const onboarding = [
  {
    icon: Building2,
    title: "Create your org",
    body: "Pick nonprofit, for-profit, or dual. Add NAICS codes, geo, and the funding categories you actually pursue.",
    time: "60 seconds",
  },
  {
    icon: Upload,
    title: "Upload 5–10 vault docs",
    body: "Past wins, annual reports, founder letters, capacity statements, partner letters. The voice agent reads these to fingerprint your voice. The drafting agent reads these to ground every claim.",
    time: "90 seconds",
  },
  {
    icon: Plug,
    title: "Connect funding sources",
    body: "Toggle SAM.gov, Grants.gov, Simpler Grants, DYCD, NY State, Candid, SBIR. We turn on the scrapers and APIs you actually need.",
    time: "30 seconds",
  },
  {
    icon: Radar,
    title: "Run first Discovery",
    body: "First scan kicks off. Your inbox gets a real fit-scored brief by tomorrow morning. From here it runs every six hours.",
    time: "60 seconds + the wait",
  },
];

export default function HowItWorksPage() {
  return (
    <main className="relative">
      {/* HERO */}
      <section className="relative overflow-hidden border-b border-white/5">
        <div className="pointer-events-none absolute inset-0 -z-10">
          <div className="absolute left-1/2 top-1/2 h-[560px] w-[1100px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[conic-gradient(from_140deg_at_50%_50%,rgba(16,185,129,0.10),rgba(56,189,248,0.04),rgba(244,114,182,0.06),rgba(16,185,129,0.10))] blur-3xl" />
        </div>

        <div className="container mx-auto px-4 pt-20 pb-24 lg:pt-28 lg:pb-28">
          <motion.div
            initial="hidden"
            animate="visible"
            variants={fadeUp}
            transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
            className="mx-auto max-w-5xl"
          >
            <Eyebrow>How it works</Eyebrow>
            <h1 className="font-semibold tracking-tight text-white">
              <span className="block text-[clamp(2.25rem,6.5vw,5.25rem)] leading-[1.04]">
                From solicitation drop
              </span>
              <span
                className="block bg-gradient-to-br from-emerald-200 via-teal-300 to-cyan-300 bg-clip-text pb-2 text-[clamp(2.25rem,6.5vw,5.25rem)] italic leading-[1.06] text-transparent"
                style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
              >
                to submission-ready PDF.
              </span>
            </h1>
            <p className="mt-10 max-w-2xl text-lg leading-relaxed text-zinc-300 md:text-xl">
              Six agents, one workspace, six stages. This is the page where curious buyers go deep —
              what each agent does, what it touches, what it never touches, and what stays in your
              hands.
              <span className="mt-3 block text-zinc-400">
                Read it carefully. Federal capture deserves a tool you actually understand.
              </span>
            </p>
          </motion.div>
        </div>
      </section>

      {/* LIFECYCLE TIMELINE — long-form vertical */}
      <section className="relative border-b border-white/5 bg-zinc-950">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-emerald-950/[0.06] to-transparent" />
        <div className="container relative mx-auto px-4 py-28">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={fadeUp}
            transition={{ duration: 0.6 }}
            className="mb-20 max-w-3xl"
          >
            <Eyebrow>The lifecycle, end-to-end</Eyebrow>
            <h2 className="text-[clamp(2rem,4.5vw,3.5rem)] font-semibold leading-[1.05] tracking-tight text-white">
              Six stages.{" "}
              <span
                className="italic text-zinc-500"
                style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
              >
                One file, worked end-to-end.
              </span>
            </h2>
            <p className="mt-6 text-[15px] leading-relaxed text-zinc-400">
              Each row is a stage. Each row tells you exactly what the agent does, what you do, and how long it actually takes.
            </p>
          </motion.div>

          <div className="mx-auto max-w-5xl">
            <div className="relative">
              {/* Vertical rule */}
              <div className="absolute left-[28px] top-2 bottom-2 w-px bg-gradient-to-b from-emerald-400/40 via-white/10 to-transparent md:left-[36px]" />

              {stages.map((s, i) => {
                const Icon = s.icon;
                return (
                  <motion.div
                    key={s.num}
                    initial={{ opacity: 0, y: 24 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-80px" }}
                    transition={{ duration: 0.55, delay: i * 0.04, ease: [0.22, 1, 0.36, 1] }}
                    className="relative pb-14 last:pb-0"
                  >
                    <div className="flex gap-6 md:gap-8">
                      {/* Node */}
                      <div className="relative z-10 flex-shrink-0">
                        <div className="flex h-14 w-14 items-center justify-center rounded-full border border-white/10 bg-zinc-950 shadow-[0_0_30px_-10px_rgba(16,185,129,0.5)] md:h-[72px] md:w-[72px]">
                          <Icon className="h-5 w-5 text-emerald-300 md:h-6 md:w-6" />
                        </div>
                      </div>

                      {/* Content */}
                      <div className="flex-1 pt-1.5 md:pt-3">
                        <div className="mb-3 flex items-baseline gap-4">
                          <span className="font-mono text-[11px] uppercase tracking-[0.22em] text-emerald-300/80">
                            {s.num} / 06
                          </span>
                          <h3 className="text-2xl font-semibold tracking-tight text-white md:text-3xl">
                            {s.name}
                          </h3>
                        </div>

                        <div className="grid gap-6 rounded-xl border border-white/5 bg-white/[0.02] p-6 md:grid-cols-2 md:p-8">
                          <div>
                            <p className="mb-2 font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500">
                              The agent
                            </p>
                            <p className="text-[14px] leading-[1.75] text-zinc-300">{s.agent}</p>
                          </div>
                          <div>
                            <p className="mb-2 font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500">
                              You
                            </p>
                            <p className="text-[14px] leading-[1.75] text-zinc-300">{s.you}</p>
                          </div>
                          <div className="md:col-span-2 md:flex md:items-center md:gap-3 md:border-t md:border-white/5 md:pt-5">
                            <Clock className="h-3.5 w-3.5 text-zinc-500" />
                            <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-zinc-500">
                              {s.time}
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* WORKFLOW NARRATIVE — log-style timeline */}
      <section className="relative border-b border-white/5">
        <div className="container mx-auto px-4 py-28">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={fadeUp}
            transition={{ duration: 0.6 }}
            className="mx-auto mb-14 max-w-3xl"
          >
            <Eyebrow>What an actual workflow looks like</Eyebrow>
            <h2 className="text-[clamp(2rem,4.5vw,3.5rem)] font-semibold leading-[1.05] tracking-tight text-white">
              Tuesday 9:14 AM.{" "}
              <span
                className="italic text-zinc-500"
                style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
              >
                A $650K NYC DYCD workforce solicitation drops.
              </span>
            </h2>
            <p className="mt-6 text-[15px] leading-relaxed text-zinc-400">
              Here&apos;s what happens by Friday. This is an illustrative scenario built from the real lifecycle — not a customer testimonial.
            </p>
          </motion.div>

          <div className="mx-auto max-w-4xl">
            <div className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-950/60 backdrop-blur">
              <div className="flex items-center justify-between border-b border-white/5 bg-white/[0.02] px-5 py-3">
                <div className="flex items-center gap-2">
                  <span className="h-2 w-2 rounded-full bg-emerald-400" />
                  <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-zinc-400">
                    proposal.log — DYCD-WLG-2026
                  </span>
                </div>
                <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-600">
                  Illustrative
                </span>
              </div>

              <div className="divide-y divide-white/5">
                {scenario.map((row, i) => (
                  <motion.div
                    key={row.stamp + row.label}
                    initial={{ opacity: 0, x: -8 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true, margin: "-30px" }}
                    transition={{ duration: 0.4, delay: i * 0.03 }}
                    className="grid grid-cols-12 gap-4 px-5 py-4 transition-colors hover:bg-white/[0.02] md:px-7 md:py-5"
                  >
                    <div className="col-span-12 md:col-span-3">
                      <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-emerald-300/80">
                        {row.stamp}
                      </p>
                      <p className="font-mono text-[10px] uppercase tracking-[0.16em] text-zinc-600">
                        {row.label}
                      </p>
                    </div>
                    <p className="col-span-12 text-[14px] leading-[1.75] text-zinc-300 md:col-span-9">
                      {row.body}
                    </p>
                  </motion.div>
                ))}
              </div>

              <div className="border-t border-white/5 bg-emerald-500/[0.04] px-5 py-4 md:px-7">
                <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-emerald-300">
                  Total wall time → 4 days · Total staff time → ~6 hours
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SIX AGENTS — profile cards */}
      <section className="relative border-b border-white/5 bg-zinc-950">
        <div className="container mx-auto px-4 py-28">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={fadeUp}
            transition={{ duration: 0.6 }}
            className="mx-auto mb-16 max-w-3xl"
          >
            <Eyebrow>The six agents</Eyebrow>
            <h2 className="text-[clamp(2rem,4.5vw,3.5rem)] font-semibold leading-[1.05] tracking-tight text-white">
              Each one has a job.{" "}
              <span
                className="italic text-zinc-500"
                style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
              >
                And a lane.
              </span>
            </h2>
            <p className="mt-6 text-[15px] leading-relaxed text-zinc-400">
              Six narrow agents in coordination beats one wide agent that quietly drifts. Each profile names the job, what it touches, and what it doesn&apos;t.
            </p>
          </motion.div>

          <div className="mx-auto grid max-w-6xl gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/5 md:grid-cols-2 lg:grid-cols-3">
            {agents.map((a, i) => {
              const Icon = a.icon;
              return (
                <motion.div
                  key={a.name}
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: i * 0.06 }}
                  className="group relative flex flex-col bg-zinc-950 p-8 transition-colors duration-500 hover:bg-zinc-900/60"
                >
                  <div className="mb-6 flex items-center justify-between">
                    <div className="flex h-11 w-11 items-center justify-center rounded-lg border border-white/10 bg-white/[0.04] transition-colors group-hover:border-emerald-400/40 group-hover:bg-emerald-400/10">
                      <Icon className="h-5 w-5 text-emerald-300" />
                    </div>
                    <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-600">
                      {String(i + 1).padStart(2, "0")} / 06
                    </span>
                  </div>
                  <h3 className="mb-3 text-xl font-semibold tracking-tight text-white">{a.name}</h3>
                  <p className="mb-5 text-[13.5px] leading-[1.7] text-zinc-400">{a.role}</p>

                  <div className="mt-auto space-y-3 border-t border-white/5 pt-5">
                    <div>
                      <p className="mb-1 font-mono text-[10px] uppercase tracking-[0.18em] text-emerald-300/80">
                        Touches
                      </p>
                      <p className="text-[12.5px] leading-[1.65] text-zinc-300">{a.touches}</p>
                    </div>
                    <div>
                      <p className="mb-1 font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">
                        Never touches
                      </p>
                      <p className="text-[12.5px] leading-[1.65] text-zinc-400">{a.doesnt}</p>
                    </div>
                  </div>

                  <div className="absolute inset-x-8 bottom-0 h-px origin-left scale-x-0 bg-gradient-to-r from-emerald-400/60 via-teal-400/40 to-transparent transition-transform duration-700 group-hover:scale-x-100" />
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* WHAT STAYS HUMAN */}
      <section className="relative border-b border-white/5">
        <div className="container mx-auto px-4 py-28">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={fadeUp}
            transition={{ duration: 0.6 }}
            className="mx-auto mb-14 max-w-4xl"
          >
            <Eyebrow>What stays human</Eyebrow>
            <h2 className="text-[clamp(2rem,4.5vw,3.5rem)] font-semibold leading-[1.05] tracking-tight text-white">
              We get you to submit-ready.{" "}
              <span
                className="italic text-zinc-500"
                style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
              >
                You decide what ships.
              </span>
            </h2>
            <p className="mt-6 max-w-2xl text-[15px] leading-relaxed text-zinc-400">
              Some things should never be automated for federal capture. Here&apos;s the line — and we don&apos;t cross it.
            </p>
          </motion.div>

          <div className="mx-auto max-w-4xl space-y-2">
            {humanOnly.map((h, i) => (
              <motion.div
                key={h.label}
                initial={{ opacity: 0, x: -10 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.04 }}
                className="group flex items-start gap-5 border-b border-white/5 py-5 transition-colors hover:bg-white/[0.02]"
              >
                <div className="mt-0.5 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full border border-white/10 bg-zinc-900">
                  <XCircle className="h-3.5 w-3.5 text-zinc-600" />
                </div>
                <div className="flex flex-1 flex-col gap-1 sm:flex-row sm:items-baseline sm:gap-6">
                  <div className="min-w-[200px]">
                    <p className="text-[15px] font-medium text-white">{h.label}</p>
                    <p className="font-mono text-[10px] uppercase tracking-[0.16em] text-zinc-500">
                      Human only
                    </p>
                  </div>
                  <p className="flex-1 text-[14px] leading-relaxed text-zinc-400">{h.body}</p>
                </div>
              </motion.div>
            ))}

            <motion.div
              initial={{ opacity: 0, x: -10 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.25 }}
              className="relative mt-6 flex items-start gap-5 overflow-hidden rounded-xl border border-emerald-400/30 bg-gradient-to-br from-emerald-500/[0.08] via-teal-500/[0.04] to-transparent p-6"
            >
              <div className="absolute -top-px left-10 right-10 h-px bg-gradient-to-r from-transparent via-emerald-400 to-transparent" />
              <div className="mt-0.5 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-emerald-400/15">
                <CheckCircle2 className="h-4 w-4 text-emerald-300" />
              </div>
              <div className="flex flex-1 flex-col gap-1 sm:flex-row sm:items-baseline sm:gap-6">
                <div className="min-w-[200px]">
                  <p className="text-[15px] font-semibold text-white">Our posture</p>
                  <p className="font-mono text-[10px] uppercase tracking-[0.16em] text-emerald-300/80">
                    submit-ready, not auto-submitted
                  </p>
                </div>
                <p className="flex-1 text-[14px] leading-relaxed text-zinc-300">
                  The platform takes you all the way to a clean, compliant, submission-ready package. The last click — and the accountability that goes with it — is yours.
                </p>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* DATA POSTURE */}
      <section className="relative border-b border-white/5 bg-zinc-950">
        <div className="container mx-auto px-4 py-28">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={fadeUp}
            transition={{ duration: 0.6 }}
            className="mx-auto max-w-4xl"
          >
            <Eyebrow>Where your data lives</Eyebrow>
            <h2 className="text-[clamp(2rem,4.5vw,3.25rem)] font-semibold leading-[1.05] tracking-tight text-white">
              Your vault is{" "}
              <span
                className="italic text-emerald-300"
                style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
              >
                yours.
              </span>
            </h2>

            <div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/5 md:grid-cols-3">
              {[
                {
                  icon: Lock,
                  title: "Tenant isolation",
                  body: "Every row carries a tenant ID. Postgres Row-Level Security enforces that no user — and no agent — reads outside your org. Verified by automated tests on every deploy.",
                },
                {
                  icon: Database,
                  title: "Voice fingerprint is yours",
                  body: "Your voice JSON lives on your org row. It is never used to train shared models, never pooled with other tenants, never shipped to a third-party vendor.",
                },
                {
                  icon: ShieldCheck,
                  title: "No training pipelines",
                  body: "We do not fine-tune on customer data. Inference happens against your retrieved context at runtime. Audit-grade activity logs are exportable for FOIA and OIG.",
                },
              ].map((d) => {
                const Icon = d.icon;
                return (
                  <div key={d.title} className="bg-zinc-950 p-8">
                    <div className="mb-5 flex h-10 w-10 items-center justify-center rounded-lg border border-white/10 bg-white/[0.04]">
                      <Icon className="h-4 w-4 text-emerald-300" />
                    </div>
                    <h3 className="mb-2 text-[16px] font-semibold tracking-tight text-white">
                      {d.title}
                    </h3>
                    <p className="text-[13px] leading-[1.7] text-zinc-400">{d.body}</p>
                  </div>
                );
              })}
            </div>

            <p className="mt-8 max-w-2xl text-[14px] leading-relaxed text-zinc-500">
              A dedicated trust page with full security architecture, sub-processors, and compliance posture is on the roadmap. Until it ships, ask us anything in a sales conversation.
            </p>
          </motion.div>
        </div>
      </section>

      {/* ONBOARDING */}
      <section className="relative border-b border-white/5">
        <div className="container mx-auto px-4 py-28">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={fadeUp}
            transition={{ duration: 0.6 }}
            className="mx-auto mb-16 max-w-3xl"
          >
            <Eyebrow>Onboarding in four moves</Eyebrow>
            <h2 className="text-[clamp(2rem,4.5vw,3.5rem)] font-semibold leading-[1.05] tracking-tight text-white">
              Tenant ready in{" "}
              <span
                className="italic text-emerald-300"
                style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
              >
                four minutes.
              </span>
            </h2>
            <p className="mt-6 text-[15px] leading-relaxed text-zinc-400">
              We mean four minutes. Not a sales call. Not a sandbox demo. Not a Calendly chain. Sign up, do these four things, run.
            </p>
          </motion.div>

          <ol className="mx-auto max-w-5xl space-y-3">
            {onboarding.map((step, i) => {
              const Icon = step.icon;
              return (
                <motion.li
                  key={step.title}
                  initial={{ opacity: 0, y: 16 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ duration: 0.5, delay: i * 0.05 }}
                  className="group relative grid grid-cols-12 items-start gap-4 rounded-xl border border-white/5 bg-white/[0.02] p-6 transition-all hover:border-emerald-400/30 hover:bg-emerald-500/[0.03] md:p-7"
                >
                  <div className="col-span-12 flex items-center gap-4 md:col-span-3">
                    <span className="font-mono text-[28px] font-light leading-none text-zinc-700 md:text-[40px]">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <div className="flex h-10 w-10 items-center justify-center rounded-md border border-white/10 bg-white/[0.04] transition-colors group-hover:border-emerald-400/40 group-hover:bg-emerald-400/10">
                      <Icon className="h-4 w-4 text-emerald-300" />
                    </div>
                  </div>
                  <div className="col-span-12 md:col-span-7">
                    <h3 className="mb-1.5 text-[17px] font-semibold tracking-tight text-white">
                      {step.title}
                    </h3>
                    <p className="text-[13.5px] leading-[1.7] text-zinc-400">{step.body}</p>
                  </div>
                  <div className="col-span-12 md:col-span-2 md:text-right">
                    <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-emerald-300/80">
                      {step.time}
                    </p>
                  </div>
                </motion.li>
              );
            })}
          </ol>

          <p className="mx-auto mt-10 max-w-2xl text-center font-mono text-[11px] uppercase tracking-[0.2em] text-zinc-500">
            First Discovery brief in your inbox by morning
          </p>
        </div>
      </section>

      {/* FINAL CTA */}
      <section className="relative overflow-hidden">
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute left-1/2 top-1/2 h-[700px] w-[1100px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[radial-gradient(closest-side,rgba(16,185,129,0.20),transparent)] blur-3xl" />
        </div>
        <div className="container relative mx-auto px-4 py-32 text-center">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
          >
            <h2 className="mx-auto max-w-3xl text-[clamp(2.25rem,5.5vw,4.5rem)] font-semibold leading-[1.02] tracking-tight text-white">
              Now you know how it works.
              <br />
              <span
                className="italic text-zinc-500"
                style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
              >
                Want to see it on your own pipeline?
              </span>
            </h2>
            <p className="mx-auto mt-8 max-w-xl text-[15px] leading-relaxed text-zinc-400">
              14-day free trial. Tenant set up in four minutes. First Discovery feed in your inbox tomorrow morning.
            </p>
            <div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row">
              <Button
                size="lg"
                asChild
                className="h-12 rounded-md bg-white px-7 text-[14px] font-medium text-zinc-950 shadow-[0_8px_40px_-8px_rgba(255,255,255,0.4)] hover:bg-zinc-100"
              >
                <Link href="/signup?next=/orgs/new&product=rfp-engine">
                  Start Free Trial
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
              <Button
                size="lg"
                variant="outline"
                asChild
                className="h-12 rounded-md border-white/15 bg-white/5 px-7 text-[14px] font-medium text-white backdrop-blur hover:bg-white/10"
              >
                <Link href="/contact-sales?product=rfp-engine">Book a Demo</Link>
              </Button>
            </div>
          </motion.div>
        </div>
      </section>
    </main>
  );
}
